import type { DoctorNotification } from "./doctorNotifications.types"

export function getDoctorNotificationsMock(): DoctorNotification[] {
  return [
    {
      id: "n1",
      kind: "queue",
      sender: { name: "Ahmed Hassan", role: "patient" },
      body: "Joined your queue — chief complaint: chest pain.",
      createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-queue",
    },
    {
      id: "n2",
      kind: "lab_result",
      title: "Lab results synced",
      body: "Troponin and CBC panels arrived from the hospital lab interface.",
      createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-patients",
    },
    {
      id: "n3",
      kind: "archive_request",
      sender: { name: "Nour El-Din", role: "assistant" },
      body: "Requested to archive Demo Patient — your approval is required.",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-patients",
      actions: [
        { id: "approve-archive", label: "Approve", variant: "primary" },
        { id: "decline-archive", label: "Decline", variant: "secondary" },
      ],
    },
    {
      id: "n4",
      kind: "ai_insight",
      title: "AI clinical insight",
      body: "2 patients in queue share overlapping cardiac risk factors. Summary draft is ready.",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-queue",
    },
    {
      id: "n5",
      kind: "appointment",
      sender: { name: "Omar Ali", role: "patient" },
      body: "Booked a follow-up today at 2:30 PM in Clinic Room 3.",
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-appointments",
    },
    {
      id: "n6",
      kind: "system",
      title: "Clinic schedule reminder",
      body: "Afternoon clinic block starts in 30 minutes. 4 patients on the expected list.",
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-appointments",
    },
    {
      id: "n7",
      kind: "vitals_alert",
      title: "Critical vitals alert",
      body: "Home BP 168/102 mmHg recorded for Fatma Nabil — threshold exceeded.",
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-patients",
      actions: [
        {
          id: "review-vitals",
          label: "Review reading",
          variant: "primary",
          href: "/doctor-patients",
        },
      ],
    },
    {
      id: "n8",
      kind: "medication_flag",
      title: "Critical medication flag",
      body: "AI detected a potential interaction between Metoprolol and a newly ordered diuretic for Sara Mahmoud.",
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-prescriptions",
      actions: [
        {
          id: "review-med",
          label: "Review chart",
          variant: "primary",
          href: "/doctor-prescriptions",
        },
        {
          id: "change-dose",
          label: "Change dose",
          variant: "secondary",
          href: "/doctor-prescriptions",
        },
        { id: "stop-med", label: "Stop medication", variant: "destructive" },
      ],
    },
    {
      id: "n8b",
      kind: "medication_flag",
      title: "Medication flag — watch",
      body: "Digoxin timing variance noted for Ahmed Hassan. Assistant marked for follow-up.",
      createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-prescriptions",
      actions: [
        {
          id: "ack-flag",
          label: "Acknowledge",
          variant: "secondary",
        },
        {
          id: "review-watch",
          label: "Review medication",
          variant: "primary",
          href: "/doctor-prescriptions",
        },
      ],
    },
    {
      id: "n9",
      kind: "prescription",
      sender: { name: "Youssef Kamal", role: "patient" },
      body: "Requested a refill for Metoprolol 50 mg.",
      createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      read: false,
      href: "/doctor-prescriptions",
      actions: [
        { id: "approve-refill", label: "Approve refill", variant: "primary" },
        { id: "deny-refill", label: "Deny", variant: "secondary" },
      ],
    },
    {
      id: "n10",
      kind: "system",
      title: "System maintenance",
      body: "Document storage will undergo brief maintenance tonight at 11:00 PM.",
      createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
      read: false,
    },
  ]
}
