import type { Doctor, Specialty } from "./doctorDirectory.types"

export const specialties: Specialty[] = [
  { id: "1", name: "Cardiology", icon: "HeartPulse" },
  { id: "2", name: "Neurology", icon: "Brain" },
  { id: "3", name: "Pediatrics", icon: "Baby" },
  { id: "4", name: "Dermatology", icon: "Stethoscope" },
  { id: "5", name: "Orthopedics", icon: "Bone" },
  { id: "6", name: "Ophthalmology", icon: "Eye" },
]

export const mockDoctors: Doctor[] = [
  {
    id: "dr1",
    name: "Dr. Sarah Ahmed",
    title: "Senior Cardiologist",
    specialty: specialties[0],
    experience: 12,
    rating: 4.9,
    reviewCount: 128,
    availability: "Available",
    nextAvailableSlot: "2026-05-14T09:00:00Z",
    fee: 500,
    location: "Sheikh Zayed, Cairo",
    hospital: "Zayed Specialized Hospital",
    languages: ["English", "Arabic"],
    about: "Dr. Sarah Ahmed is a leading cardiologist with over 12 years of experience in managing complex heart conditions.",
  },
  {
    id: "dr2",
    name: "Dr. Mohamed Ali",
    title: "Consultant Neurologist",
    specialty: specialties[1],
    experience: 15,
    rating: 4.8,
    reviewCount: 95,
    availability: "Limited",
    nextAvailableSlot: "2026-05-15T11:30:00Z",
    fee: 600,
    location: "Maadi, Cairo",
    hospital: "Maadi Medical Center",
    languages: ["English", "Arabic", "French"],
    about: "Specialized in neurological disorders and brain health with extensive research in stroke prevention.",
  },
  {
    id: "dr3",
    name: "Dr. Laila Hassan",
    title: "Pediatric Specialist",
    specialty: specialties[2],
    experience: 8,
    rating: 4.7,
    reviewCount: 210,
    availability: "Available",
    nextAvailableSlot: "2026-05-14T14:00:00Z",
    fee: 400,
    location: "New Cairo, Cairo",
    hospital: "Cure Hospital",
    languages: ["English", "Arabic"],
    about: "Dedicated to providing the best healthcare for children from infancy through adolescence.",
  },
  {
    id: "dr4",
    name: "Dr. Kareem Mahmoud",
    title: "Dermatologist",
    specialty: specialties[3],
    experience: 10,
    rating: 4.9,
    reviewCount: 156,
    availability: "Available",
    nextAvailableSlot: "2026-05-14T10:00:00Z",
    fee: 450,
    location: "Dokki, Giza",
    hospital: "International Clinic",
    languages: ["English", "Arabic"],
    about: "Expert in clinical and cosmetic dermatology with a focus on skin cancer screening.",
  },
  {
    id: "dr5",
    name: "Dr. Ahmed Mansour",
    title: "Orthopedic Surgeon",
    specialty: specialties[4],
    experience: 20,
    rating: 5.0,
    reviewCount: 340,
    availability: "Unavailable",
    nextAvailableSlot: "2026-05-20T08:00:00Z",
    fee: 700,
    location: "Nasr City, Cairo",
    hospital: "Al-Ahly Hospital",
    languages: ["English", "Arabic", "German"],
    about: "Renowned orthopedic surgeon specializing in joint replacement and sports injuries.",
  },
]
