import type { QueuePatient, QueueStats } from "./doctorQueue.types"

export const mockQueueStats: QueueStats = {
  totalToday: 14,
  scheduled: 4,
  arrived: 0,
  inWaiting: 5,
  inConsultation: 1,
  completed: 3,
  noShow: 1,
  avgWaitMin: 24,
  currentWaitMin: 18,
}

const now = new Date()
const t = (h: number, m: number) => {
  const d = new Date(now)
  d.setHours(h, m, 0, 0)
  return d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
}

export const mockQueuePatients: QueuePatient[] = [
  {
    id: "p-001",
    queueEntryId: "q-001",
    fullName: "Ahmed Al-Rashid",
    age: 58,
    gender: "male",
    condition: "Essential Hypertension, T2DM",
    visitType: "follow-up",
    priority: "normal",
    status: "in-consultation",
    scheduledTime: "09:00",
    arrivedAt: t(8, 55),
    waitingSince: t(8, 56),
    startedAt: t(9, 3),
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: "Room 3",
    notes: "Review BP readings, check HbA1c results",
    hasAllergies: true,
    activeMedications: 4,
    vitalAlerts: 1,
    phoneNumber: "+20 100 123 4567",
  },
  {
    id: "p-003",
    queueEntryId: "q-002",
    fullName: "Mohamed Youssef",
    age: 71,
    gender: "male",
    condition: "Heart Failure (NYHA II), CAD",
    visitType: "follow-up",
    priority: "urgent",
    status: "waiting",
    scheduledTime: "09:20",
    arrivedAt: t(9, 15),
    waitingSince: t(9, 16),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 30,
    roomNumber: null,
    notes: "Worsening dyspnea x3 days. Needs urgent eval.",
    hasAllergies: false,
    activeMedications: 6,
    vitalAlerts: 3,
    phoneNumber: "+20 111 456 7890",
  },
  {
    id: "p-005",
    queueEntryId: "q-003",
    fullName: "Omar Abdel-Aziz",
    age: 66,
    gender: "male",
    condition: "Aortic Stenosis (Moderate)",
    visitType: "follow-up",
    priority: "normal",
    status: "waiting",
    scheduledTime: "09:40",
    arrivedAt: t(9, 30),
    waitingSince: t(9, 31),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: null,
    notes: "",
    hasAllergies: false,
    activeMedications: 3,
    vitalAlerts: 0,
    phoneNumber: "+20 122 567 8901",
  },
  {
    id: "p-012",
    queueEntryId: "q-004",
    fullName: "Karim Nabil",
    age: 45,
    gender: "male",
    condition: "New chest pain evaluation",
    visitType: "walk-in",
    priority: "urgent",
    status: "waiting",
    scheduledTime: "",
    arrivedAt: t(9, 45),
    waitingSince: t(9, 46),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 30,
    roomNumber: null,
    notes: "Walk-in. Chest pain onset today at 7am. No prior cardiac history.",
    hasAllergies: false,
    activeMedications: 0,
    vitalAlerts: 2,
    phoneNumber: "+20 100 999 3344",
  },
  {
    id: "p-010",
    queueEntryId: "q-005",
    fullName: "Amira Farouk",
    age: 68,
    gender: "female",
    condition: "Post-MI Follow-up",
    visitType: "follow-up",
    priority: "normal",
    status: "waiting",
    scheduledTime: "10:20",
    arrivedAt: t(10, 10),
    waitingSince: t(10, 11),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 25,
    roomNumber: null,
    notes: "6-week post-MI check. Review echo results.",
    hasAllergies: false,
    activeMedications: 5,
    vitalAlerts: 0,
    phoneNumber: "+20 155 678 9012",
  },
  {
    id: "p-016",
    queueEntryId: "q-006",
    fullName: "Hoda Kamal",
    age: 49,
    gender: "female",
    condition: "Hypertension (Stage I)",
    visitType: "follow-up",
    priority: "normal",
    status: "waiting",
    scheduledTime: "10:40",
    arrivedAt: t(10, 35),
    waitingSince: t(10, 36),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 15,
    roomNumber: null,
    notes: "",
    hasAllergies: false,
    activeMedications: 1,
    vitalAlerts: 0,
    phoneNumber: "+20 100 445 6677",
  },
  {
    id: "p-002",
    queueEntryId: "q-007",
    fullName: "Fatima Hassan",
    age: 51,
    gender: "female",
    condition: "Atrial Fibrillation",
    visitType: "follow-up",
    priority: "normal",
    status: "scheduled",
    scheduledTime: "10:00",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 15,
    roomNumber: null,
    notes: "Discuss anticoagulation options",
    hasAllergies: true,
    activeMedications: 3,
    vitalAlerts: 0,
    phoneNumber: "+20 100 234 5678",
  },
  {
    id: "p-008",
    queueEntryId: "q-008",
    fullName: "Nadia Selim",
    age: 61,
    gender: "female",
    condition: "Dyslipidemia, Hypothyroidism",
    visitType: "follow-up",
    priority: "normal",
    status: "scheduled",
    scheduledTime: "11:00",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 15,
    roomNumber: null,
    notes: "",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 133 789 0123",
  },
  {
    id: "p-009",
    queueEntryId: "q-009",
    fullName: "Hassan Mahmoud",
    age: 56,
    gender: "male",
    condition: "Hypertension (Stage II), Obesity",
    visitType: "follow-up",
    priority: "normal",
    status: "scheduled",
    scheduledTime: "11:20",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: null,
    notes: "Weight management discussion",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 144 890 1234",
  },
  {
    id: "p-006",
    queueEntryId: "q-010",
    fullName: "Layla Mostafa",
    age: 36,
    gender: "female",
    condition: "Palpitations, Anxiety",
    visitType: "new",
    priority: "normal",
    status: "scheduled",
    scheduledTime: "11:40",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 25,
    roomNumber: null,
    notes: "New patient referral from GP",
    hasAllergies: false,
    activeMedications: 1,
    vitalAlerts: 0,
    phoneNumber: "+20 100 345 6789",
  },
  {
    id: "p-011",
    queueEntryId: "q-011",
    fullName: "Tarek Adel",
    age: 63,
    gender: "male",
    condition: "Post-stent follow-up",
    visitType: "post-procedure",
    priority: "normal",
    status: "scheduled",
    scheduledTime: "12:00",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 15,
    roomNumber: null,
    notes: "2-week post-stent check. On dual antiplatelet.",
    hasAllergies: true,
    activeMedications: 4,
    vitalAlerts: 0,
    phoneNumber: "+20 166 901 2345",
  },
  {
    id: "p-013",
    queueEntryId: "q-012",
    fullName: "Dina Samy",
    age: 52,
    gender: "female",
    condition: "Hypertension, T2DM",
    visitType: "follow-up",
    priority: "normal",
    status: "completed",
    scheduledTime: "08:00",
    arrivedAt: "07:50",
    waitingSince: "07:51",
    startedAt: "08:02",
    completedAt: "08:18",
    estimatedDurationMin: 15,
    roomNumber: "Room 3",
    notes: "",
    hasAllergies: false,
    activeMedications: 3,
    vitalAlerts: 0,
    phoneNumber: "+20 100 456 7890",
  },
  {
    id: "p-014",
    queueEntryId: "q-013",
    fullName: "Ali Fawzy",
    age: 70,
    gender: "male",
    condition: "Atrial Flutter",
    visitType: "follow-up",
    priority: "normal",
    status: "completed",
    scheduledTime: "08:20",
    arrivedAt: "08:15",
    waitingSince: "08:16",
    startedAt: "08:22",
    completedAt: "08:40",
    estimatedDurationMin: 20,
    roomNumber: "Room 3",
    notes: "",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 100 567 8901",
  },
  {
    id: "p-017",
    queueEntryId: "q-014",
    fullName: "Sami Rizk",
    age: 59,
    gender: "male",
    condition: "Hypertension, Dyslipidemia",
    visitType: "follow-up",
    priority: "normal",
    status: "completed",
    scheduledTime: "08:40",
    arrivedAt: "08:35",
    waitingSince: "08:36",
    startedAt: "08:42",
    completedAt: "08:55",
    estimatedDurationMin: 15,
    roomNumber: "Room 3",
    notes: "",
    hasAllergies: false,
    activeMedications: 3,
    vitalAlerts: 0,
    phoneNumber: "+20 100 678 9012",
  },
  {
    id: "p-015",
    queueEntryId: "q-015",
    fullName: "Mona Ashraf",
    age: 44,
    gender: "female",
    condition: "New cardiac evaluation",
    visitType: "new",
    priority: "normal",
    status: "no-show",
    scheduledTime: "08:40",
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 25,
    roomNumber: null,
    notes: "Did not show up. Called — no answer.",
    hasAllergies: false,
    activeMedications: 0,
    vitalAlerts: 0,
    phoneNumber: "+20 100 789 0123",
  },
]
