import type { ContactItem, ChatMessageItem, ContactDetails } from "./assistantChats.types"

const AVATAR_COLORS = [
  "bg-violet-500",
  "bg-blue-500",
  "bg-rose-400",
  "bg-amber-500",
  "bg-emerald-500",
  "bg-cyan-500",
  "bg-pink-500",
  "bg-indigo-500",
] as const

export const MOCK_FAVOURITES: ContactItem[] = [
  {
    id: "1",
    name: "Anthony Lewis",
    avatarColor: AVATAR_COLORS[0],
    lastMessage: "is typing",
    lastMessageType: "typing",
    time: "02:40 PM",
    unreadCount: 0,
    isOnline: true,
    isFavourite: true,
    isPinned: true,
  },
  {
    id: "2",
    name: "Elliot Murray",
    avatarColor: AVATAR_COLORS[1],
    lastMessage: "Document",
    lastMessageType: "document",
    time: "06:12 AM",
    unreadCount: 0,
    isOnline: true,
    isFavourite: true,
    statusIcon: "double-check",
  },
  {
    id: "3",
    name: "Stephan Peralt",
    avatarColor: AVATAR_COLORS[2],
    lastMessage: "Missed Video Call",
    lastMessageType: "missed_call",
    time: "03:15 AM",
    unreadCount: 0,
    isOnline: true,
    isFavourite: true,
    isPinned: true,
  },
  {
    id: "4",
    name: "Rebecca Smtih",
    avatarColor: AVATAR_COLORS[3],
    lastMessage: "Hi How are you 🔥",
    lastMessageType: "text",
    time: "Sunday",
    unreadCount: 25,
    isOnline: true,
    isFavourite: true,
  },
  {
    id: "5",
    name: "Harvey Smith",
    avatarColor: AVATAR_COLORS[4],
    lastMessage: "Haha oh man 🔥",
    lastMessageType: "text",
    time: "03:15 AM",
    unreadCount: 12,
    isOnline: true,
    isFavourite: true,
    isPinned: true,
  },
]

export const MOCK_DIRECT_MESSAGES: ContactItem[] = [
  {
    id: "6",
    name: "Lori Broaddus",
    avatarColor: AVATAR_COLORS[5],
    lastMessage: "Do you know which...",
    lastMessageType: "text",
    time: "02:40 PM",
    unreadCount: 0,
    isOnline: true,
    isFavourite: false,
    statusIcon: "heart",
  },
  {
    id: "7",
    name: "Brian Villalobos",
    avatarColor: AVATAR_COLORS[6],
    lastMessage: "Do you know which...",
    lastMessageType: "text",
    time: "06:12 AM",
    unreadCount: 0,
    isOnline: true,
    isFavourite: false,
    isPinned: true,
    statusIcon: "double-check",
  },
]

export const MOCK_MESSAGES: ChatMessageItem[] = [
  {
    id: "m1",
    senderName: "John Steven",
    time: "8:55 PM",
    isOutgoing: false,
    contentType: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: "m2",
    senderName: "John Smith",
    time: "8:55 PM",
    isOutgoing: true,
    contentType: "text",
    text: "Sed ut perspiciatis unde omnis iste natus error accusantium doloremque laudantium",
  },
  {
    id: "m3",
    senderName: "John Steven",
    time: "8:55 PM",
    isOutgoing: false,
    contentType: "image",
    images: ["/images/placeholder-1.jpg", "/images/placeholder-2.jpg"],
  },
  {
    id: "m4",
    senderName: "John Smith",
    time: "8:55 PM",
    isOutgoing: true,
    contentType: "file",
    fileName: "admin_v1.0.zip",
    fileSize: "25mb Seprate file",
  },
  {
    id: "m5",
    senderName: "John Steven",
    time: "8:55 PM",
    isOutgoing: false,
    contentType: "text",
    text: "You wait for notice. Consectetuorem ipsum dolor sit? OK?",
  },
  {
    id: "m6",
    senderName: "John Smith",
    time: "8:55 PM",
    isOutgoing: true,
    contentType: "link",
    text: "Sed ut perspiciatis unde omnis iste natus error accusantium doloremque laudantium",
  },
]

export const MOCK_CONTACT_DETAILS: ContactDetails = {
  name: "John Doe",
  subtitle: "Newwork",
  avatarColor: AVATAR_COLORS[1],
  company: "Company Name",
  role: "Co-founder",
  phone: "+1 123 456 7890",
  email: "info@example.com",
  sharedMediaCount: 345,
  sharedPhotos: Array.from({ length: 8 }, (_, i) => `/images/media-${i + 1}.jpg`),
  notificationsEnabled: true,
  isFavourite: true,
  isMuted: false,
}
