import type { AssistantDashboardData } from "./assistantDashboard.types"

export const mockAssistantDashboard: AssistantDashboardData = {
  assistant: {
    id: "AST-2045",
    fullName: "Amira Hassan",
    department: "Cardiology",
    experienceYears: 4,
  },
  stats: {
    activeTasks: 8,
    assignedCases: 12,
    hoursThisWeek: 36,
    supportedDoctors: 3,
  },
  tasks: [
    {
      id: "task-1",
      title: "Review patient vitals for PT-1842",
      description: "Daily vital signs check for Sara Ahmed",
      status: "in-progress",
      dueAt: "2026-04-11T18:00:00Z",
      assignedBy: "Dr. Mahmoud Ali",
    },
    {
      id: "task-2",
      title: "Prepare appointment summary",
      description: "Document and summarize findings from today's appointments",
      status: "pending",
      dueAt: "2026-04-12T17:00:00Z",
      assignedBy: "Dr. Hana Farid",
    },
    {
      id: "task-3",
      title: "Follow-up call with patient",
      description: "Check on PT-2011 (Omar Hassan) post-treatment recovery",
      status: "pending",
      dueAt: "2026-04-13T10:00:00Z",
      assignedBy: "Dr. Mahmoud Ali",
    },
    {
      id: "task-4",
      title: "Data entry for lab results",
      description: "Input recent lab work results into patient records",
      status: "completed",
      dueAt: "2026-04-10T16:00:00Z",
      assignedBy: "Medical Records",
    },
  ],
  assignedCases: [
    {
      id: "case-1",
      patientName: "Sara Ahmed",
      patientId: "PT-1842",
      primaryDoctor: "Dr. Mahmoud Ali",
      condition: "Hypertension (controlled)",
      assignedAt: "2026-03-15T09:00:00Z",
      status: "active",
    },
    {
      id: "case-2",
      patientName: "Omar Hassan",
      patientId: "PT-2011",
      primaryDoctor: "Dr. Mahmoud Ali",
      condition: "Arrhythmia follow-up",
      assignedAt: "2026-03-22T14:30:00Z",
      status: "active",
    },
    {
      id: "case-3",
      patientName: "Laila Nasser",
      patientId: "PT-3099",
      primaryDoctor: "Dr. Hana Farid",
      condition: "Cholesterol management",
      assignedAt: "2026-03-28T10:15:00Z",
      status: "monitoring",
    },
    {
      id: "case-4",
      patientName: "Ahmed Mohamed",
      patientId: "PT-2155",
      primaryDoctor: "Dr. Karim El-Sayed",
      condition: "Post-MI rehabilitation",
      assignedAt: "2026-03-01T11:00:00Z",
      status: "active",
    },
  ],
  doctorSupport: [
    {
      id: "doc-1",
      doctorName: "Dr. Mahmoud Ali",
      department: "Cardiology",
      supportType: "patient-monitoring",
      casesSupported: 6,
      lastInteraction: "2026-04-11T14:22:00Z",
    },
    {
      id: "doc-2",
      doctorName: "Dr. Hana Farid",
      department: "Cardiology",
      supportType: "documentation",
      casesSupported: 4,
      lastInteraction: "2026-04-10T09:15:00Z",
    },
    {
      id: "doc-3",
      doctorName: "Dr. Karim El-Sayed",
      department: "Cardiology",
      supportType: "consultation",
      casesSupported: 2,
      lastInteraction: "2026-04-09T16:45:00Z",
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      summary: "Completed vital signs review for Sara Ahmed",
      type: "task-completed",
      at: "2026-04-10T17:30:00Z",
    },
    {
      id: "act-2",
      summary: "Updated case notes for Omar Hassan's appointment",
      type: "case-updated",
      at: "2026-04-10T16:00:00Z",
    },
    {
      id: "act-3",
      summary: "Provided consultation support to Dr. Karim El-Sayed",
      type: "support-provided",
      at: "2026-04-09T11:20:00Z",
    },
    {
      id: "act-4",
      summary: "Submitted comprehensive patient report for PT-3099",
      type: "document-submitted",
      at: "2026-04-08T14:15:00Z",
    },
  ],
}
