import type { MedicationsPageData } from "./medications.types"

// Use a fixed date to avoid hydration mismatches between server and client
const FIXED_DATE = new Date("2026-04-14T12:00:00Z")

function makeDate(dayOffset: number, hours: number, minutes: number): string {
  const d = new Date(FIXED_DATE)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

export const MOCK_MEDICATIONS: MedicationsPageData = {
  medications: [
    {
      id: "med-1",
      name: "Aspirin",
      dose: "75 mg",
      frequency: "Once daily",
      duration: "Ongoing (no end date)",
      type: "antiplatelets",
      compliance: "good",
      sideEffects: "Minor stomach irritation",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-180, 0, 0),
      lastTakenAt: makeDate(0, 8, 14),
      nextDoseAt: makeDate(1, 8, 0),
      instructions: "Take with food. Low-dose for heart protection.",
      timeOfDay: ["morning"],
      remainingRefills: 8,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-2",
      name: "Metoprolol",
      dose: "50 mg",
      frequency: "Twice daily",
      duration: "Ongoing (no end date)",
      type: "antihypertensives",
      compliance: "good",
      sideEffects: "Fatigue, dizziness",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-120, 0, 0),
      lastTakenAt: makeDate(0, 8, 16),
      nextDoseAt: makeDate(0, 21, 0),
      instructions: "Take with meals. Do not stop suddenly.",
      timeOfDay: ["morning"],
      remainingRefills: 5,
      adherenceHistory: [true, false, true, false, true, true, true],
    },
    {
      id: "med-3",
      name: "Atorvastatin",
      dose: "20 mg",
      frequency: "Once daily",
      duration: "1 year",
      type: "statins",
      compliance: "good",
      sideEffects: "Mild muscle ache occasionally",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-90, 0, 0),
      lastTakenAt: makeDate(0, 20, 10),
      nextDoseAt: makeDate(1, 21, 0),
      instructions: "Take at bedtime with water. Avoid grapefruit juice.",
      timeOfDay: ["evening"],
      remainingRefills: 3,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-4",
      name: "Metformin",
      dose: "500 mg",
      frequency: "Twice daily",
      duration: "Ongoing (no end date)",
      type: "diabetes_medications",
      compliance: "good",
      sideEffects: "Nausea, stomach upset",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-120, 0, 0),
      lastTakenAt: makeDate(0, 13, 0),
      nextDoseAt: makeDate(0, 20, 0),
      instructions: "Take with meals to reduce stomach upset. Stay hydrated.",
      timeOfDay: ["morning", "evening"],
      remainingRefills: 5,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-5",
      name: "Metoprolol",
      dose: "50 mg",
      frequency: "Twice daily",
      duration: "3 months",
      type: "antihypertensives",
      compliance: "poor",
      sideEffects: "Fatigue, dizziness",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-120, 0, 0),
      lastTakenAt: makeDate(-2, 21, 0),
      nextDoseAt: makeDate(-1, 23, 0),
      instructions: "Take with meals. Do not stop suddenly.",
      timeOfDay: ["evening"],
      remainingRefills: 5,
      adherenceHistory: [true, true, true, true, true, false, false],
    },
    {
      id: "med-6",
      name: "Warfarin",
      dose: "5 mg",
      frequency: "Once daily",
      duration: "6 months",
      type: "anticoagulants",
      compliance: "poor",
      sideEffects: "Easy bruising, prolonged bleeding from cuts",
      status: "active",
      prescribedBy: "Dr. Mai Ramadan",
      prescribedAt: makeDate(-45, 0, 0),
      lastTakenAt: makeDate(-1, 18, 0),
      nextDoseAt: makeDate(0, 18, 0),
      instructions: "Take at the same time every day. Avoid sudden dietary changes in vitamin K intake. Regular INR checks required.",
      timeOfDay: ["evening"],
      remainingRefills: 1,
      adherenceHistory: [true, false, true, true, false, true, true],
    },
    {
      id: "med-7",
      name: "Lisinopril",
      dose: "10 mg",
      frequency: "Once daily",
      duration: "Ongoing (no end date)",
      type: "antihypertensives",
      compliance: "good",
      status: "active",
      prescribedBy: "Dr. Youssef Ibrahim",
      prescribedAt: makeDate(-60, 0, 0),
      lastTakenAt: makeDate(0, 7, 30),
      nextDoseAt: makeDate(1, 7, 30),
      instructions: "Take in the morning. Monitor blood pressure regularly.",
      timeOfDay: ["morning"],
      remainingRefills: 2,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-8",
      name: "Furosemide",
      dose: "40 mg",
      frequency: "Once daily",
      duration: "1 month",
      type: "diuretics",
      compliance: "good",
      sideEffects: "Frequent urination, dizziness",
      status: "active",
      prescribedBy: "Dr. Hossam El-Sayed",
      prescribedAt: makeDate(-30, 0, 0),
      lastTakenAt: makeDate(0, 7, 0),
      nextDoseAt: makeDate(1, 7, 0),
      instructions: "Take in the morning to avoid nighttime urination. Monitor weight daily.",
      timeOfDay: ["morning"],
      remainingRefills: 4,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-9",
      name: "Vitamin D3",
      dose: "1000 IU",
      frequency: "Once weekly",
      duration: "3 months",
      type: "statins",
      compliance: "good",
      status: "active",
      prescribedBy: "Dr. Youssef Ibrahim",
      prescribedAt: makeDate(-200, 0, 0),
      lastTakenAt: makeDate(-3, 9, 0),
      nextDoseAt: makeDate(4, 9, 0),
      instructions: "Take with a fatty meal for better absorption.",
      timeOfDay: ["morning"],
      remainingRefills: 6,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-10",
      name: "Amiodarone",
      dose: "200 mg",
      frequency: "Once daily",
      duration: "3 months",
      type: "antiarrhythmics",
      compliance: "good",
      sideEffects: "Photosensitivity, thyroid changes",
      status: "paused",
      prescribedBy: "Dr. Mai Ramadan",
      prescribedAt: makeDate(-150, 0, 0),
      lastTakenAt: makeDate(-10, 12, 0),
      instructions: "Paused pending thyroid function review. Do not resume without doctor approval.",
      timeOfDay: ["morning"],
      remainingRefills: 0,
      adherenceHistory: [true, true, true, true, true, true, true],
    },
  ],
  doseLog: [
    { id: "log-1", medicationId: "med-1", takenAt: makeDate(0, 8, 0), skipped: false },
    { id: "log-2", medicationId: "med-2", takenAt: makeDate(0, 8, 0), skipped: false },
    { id: "log-3", medicationId: "med-3", takenAt: makeDate(0, 7, 30), skipped: false },
    { id: "log-4", medicationId: "med-4", takenAt: makeDate(0, 8, 0), skipped: false },
    { id: "log-5", medicationId: "med-6", takenAt: makeDate(0, 7, 0), skipped: false },
    { id: "log-6", medicationId: "med-2", takenAt: makeDate(0, 13, 0), skipped: false },
    { id: "log-7", medicationId: "med-5", takenAt: makeDate(-1, 18, 0), skipped: true },
  ],
  stats: {
    totalActive: 9,
    takenToday: 7,
    dueToday: 10,
    adherencePercent: 82,
  },
}
