import type { InboxData, InboxMessage } from "./inbox.types"

export const mockInboxMessages: InboxMessage[] = [
  {
    id: "msg-1",
    type: "task",
    status: "unread",
    priority: "high",
    sender: {
      name: "Dr. Mahmoud Ali",
      role: "Cardiologist",
    },
    subject: "Urgent: Review patient vitals for PT-1842",
    preview: "Patient Sara Ahmed showing elevated blood pressure readings. Please review immediately and update records.",
    body: "Patient Sara Ahmed (PT-1842) has shown consistently elevated blood pressure readings over the past 24 hours. Please review the vitals chart and update the patient records accordingly. Contact Dr. Ali if readings continue to rise.",
    createdAt: "2026-05-07T09:30:00Z",
    actionUrl: "/assistant-patients/PT-1842",
    actionLabel: "View Patient",
  },
  {
    id: "msg-2",
    type: "appointment",
    status: "unread",
    priority: "normal",
    sender: {
      name: "System",
      role: "Automated",
    },
    subject: "New appointment scheduled",
    preview: "Omar Hassan has been scheduled for a follow-up appointment on May 10, 2026 at 10:00 AM.",
    body: "A new follow-up appointment has been scheduled for Omar Hassan (PT-2011) on May 10, 2026 at 10:00 AM with Dr. Mahmoud Ali. Please prepare the patient file and necessary documentation.",
    createdAt: "2026-05-07T08:15:00Z",
    actionUrl: "/assistant-appointments",
    actionLabel: "View Appointments",
  },
  {
    id: "msg-3",
    type: "doctor",
    status: "unread",
    priority: "normal",
    sender: {
      name: "Dr. Hana Farid",
      role: "Cardiologist",
    },
    subject: "Lab results review needed",
    preview: "Please review the latest cholesterol panel for Laila Nasser and prepare a summary for my review.",
    body: "The latest cholesterol panel for Laila Nasser (PT-3099) has arrived. Please review the results, update her chart, and prepare a summary report for my review during our next rounds.",
    createdAt: "2026-05-06T16:45:00Z",
    actionUrl: "/assistant-patients/PT-3099",
    actionLabel: "View Patient",
  },
  {
    id: "msg-4",
    type: "system",
    status: "read",
    priority: "low",
    sender: {
      name: "ICARE-CVD System",
      role: "System",
    },
    subject: "Weekly summary report",
    preview: "Your weekly activity summary is now available. You completed 12 tasks and supported 3 doctors this week.",
    body: "Weekly Activity Summary (April 29 - May 5, 2026):\n\n- Tasks Completed: 12\n- Doctors Supported: 3\n- Patients Assisted: 18\n- Documentation Hours: 14\n\nGreat work! Keep up the excellent performance.",
    createdAt: "2026-05-06T00:00:00Z",
    readAt: "2026-05-06T08:30:00Z",
  },
  {
    id: "msg-5",
    type: "patient",
    status: "read",
    priority: "normal",
    sender: {
      name: "Ahmed Mohamed",
      role: "Patient",
    },
    subject: "Question about medication",
    preview: "I have a question about my post-MI medication dosage. Can you please help clarify?",
    body: "Hi, I'm Ahmed Mohamed (PT-2155). I've been prescribed new medication as part of my post-MI rehabilitation, and I have some questions about the dosage timing. Can you please help clarify or schedule a call with my doctor?",
    createdAt: "2026-05-05T14:20:00Z",
    readAt: "2026-05-05T15:00:00Z",
    actionUrl: "/assistant-patients/PT-2155",
    actionLabel: "Respond",
  },
  {
    id: "msg-6",
    type: "task",
    status: "archived",
    priority: "normal",
    sender: {
      name: "Medical Records",
      role: "Department",
    },
    subject: "Data entry for lab results",
    preview: "Please input the recent lab work results into patient records by end of day.",
    body: "Recent lab work results need to be entered into patient records. Please complete this task by end of day today. Contact Medical Records if you have any questions about the data format.",
    createdAt: "2026-05-04T10:00:00Z",
    readAt: "2026-05-04T11:30:00Z",
    archivedAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "msg-7",
    type: "appointment",
    status: "read",
    priority: "urgent",
    sender: {
      name: "System",
      role: "Automated",
    },
    subject: "Appointment cancelled",
    preview: "Patient appointment for Sara Ahmed has been cancelled due to emergency.",
    body: "URGENT: The appointment for Sara Ahmed (PT-1842) scheduled for May 7, 2026 at 2:00 PM has been cancelled due to a hospital emergency. Please notify the patient and reschedule at the earliest convenience.",
    createdAt: "2026-05-04T08:00:00Z",
    readAt: "2026-05-04T08:15:00Z",
  },
]

export const mockInboxData: InboxData = {
  messages: mockInboxMessages,
  stats: {
    total: mockInboxMessages.length,
    unread: mockInboxMessages.filter((m) => m.status === "unread").length,
    read: mockInboxMessages.filter((m) => m.status === "read").length,
    archived: mockInboxMessages.filter((m) => m.status === "archived").length,
  },
  filters: {},
}
