import type { DoctorAppointmentsPageData } from "./doctorAppointments.types"

const now = new Date()

function makeDate(dayOffset: number, hours: number, minutes: number): string {
  const d = new Date(now)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

export const MOCK_DOCTOR_APPOINTMENTS: DoctorAppointmentsPageData = {
  appointments: [
    {
      id: "appt-001",
      confirmationCode: "CVD-8A3F",
      scheduledAt: makeDate(0, 9, 0),
      patient: {
        id: "pat-101",
        fullName: "Ahmed Hassan",
        age: 58,
        gender: "male",
        condition: "Hypertension, Type 2 Diabetes",
      },
      department: "Cardiology",
      reason: "Follow-up on blood pressure medication adjustment",
      symptoms: "Occasional dizziness, fatigue",
      visitType: "clinic",
      status: "confirmed",
      createdAt: makeDate(-5, 0, 0),
    },
    {
      id: "appt-002",
      confirmationCode: "CVD-2B7E",
      scheduledAt: makeDate(0, 10, 30),
      patient: {
        id: "pat-102",
        fullName: "Fatima Al-Rashid",
        age: 45,
        gender: "female",
        condition: "Atrial fibrillation",
      },
      department: "Cardiology",
      reason: "Routine cardiac monitoring",
      visitType: "virtual",
      status: "scheduled",
      createdAt: makeDate(-3, 0, 0),
    },
    {
      id: "appt-003",
      confirmationCode: "CVD-5D1C",
      scheduledAt: makeDate(0, 13, 0),
      patient: {
        id: "pat-103",
        fullName: "Mohamed Youssef",
        age: 67,
        gender: "male",
        condition: "Coronary artery disease",
      },
      department: "Cardiology",
      reason: "Post-angioplasty follow-up",
      symptoms: "Mild chest discomfort on exertion",
      visitType: "clinic",
      status: "scheduled",
      createdAt: makeDate(-2, 0, 0),
    },
    {
      id: "appt-004",
      confirmationCode: "CVD-9E4A",
      scheduledAt: makeDate(1, 9, 30),
      patient: {
        id: "pat-104",
        fullName: "Sara Ibrahim",
        age: 52,
        gender: "female",
        condition: "Heart valve disease",
      },
      department: "Cardiology",
      reason: "Echocardiogram review",
      visitType: "clinic",
      status: "confirmed",
      createdAt: makeDate(-7, 0, 0),
    },
    {
      id: "appt-005",
      confirmationCode: "CVD-1F8D",
      scheduledAt: makeDate(1, 11, 0),
      patient: {
        id: "pat-105",
        fullName: "Omar Khalil",
        age: 61,
        gender: "male",
        condition: "Heart failure (NYHA Class II)",
      },
      department: "Cardiology",
      reason: "Medication review and dose adjustment",
      symptoms: "Shortness of breath, ankle swelling",
      visitType: "virtual",
      status: "scheduled",
      createdAt: makeDate(-4, 0, 0),
    },
    {
      id: "appt-006",
      confirmationCode: "CVD-3G6B",
      scheduledAt: makeDate(2, 14, 0),
      patient: {
        id: "pat-106",
        fullName: "Nour El-Din",
        age: 39,
        gender: "male",
        condition: "Hypertrophic cardiomyopathy",
      },
      department: "Cardiology",
      reason: "Annual cardiac evaluation",
      visitType: "clinic",
      status: "scheduled",
      createdAt: makeDate(-10, 0, 0),
    },
    {
      id: "appt-007",
      confirmationCode: "CVD-7H2K",
      scheduledAt: makeDate(3, 10, 0),
      patient: {
        id: "pat-107",
        fullName: "Layla Mansour",
        age: 72,
        gender: "female",
        condition: "Peripheral artery disease",
      },
      department: "Cardiology",
      reason: "Leg pain assessment follow-up",
      symptoms: "Cramping in calves when walking",
      visitType: "clinic",
      status: "confirmed",
      createdAt: makeDate(-6, 0, 0),
    },
    {
      id: "appt-008",
      confirmationCode: "CVD-4J9M",
      scheduledAt: makeDate(-1, 9, 0),
      patient: {
        id: "pat-108",
        fullName: "Khaled Abbas",
        age: 55,
        gender: "male",
        condition: "Atherosclerosis",
      },
      department: "Cardiology",
      reason: "Lipid panel results discussion",
      visitType: "clinic",
      status: "completed",
      notes: "Patient lipid levels improving. Continue statin therapy. Schedule follow-up in 3 months.",
      createdAt: makeDate(-8, 0, 0),
    },
    {
      id: "appt-009",
      confirmationCode: "CVD-6L0N",
      scheduledAt: makeDate(-2, 11, 30),
      patient: {
        id: "pat-109",
        fullName: "Amira Soliman",
        age: 48,
        gender: "female",
        condition: "Mitral valve prolapse",
      },
      department: "Cardiology",
      reason: "Annual check-up",
      visitType: "virtual",
      status: "completed",
      notes: "Stable condition. No changes to treatment plan. Reassured patient about benign prognosis.",
      createdAt: makeDate(-12, 0, 0),
    },
    {
      id: "appt-010",
      confirmationCode: "CVD-8P3Q",
      scheduledAt: makeDate(-3, 15, 0),
      patient: {
        id: "pat-110",
        fullName: "Youssef Gamal",
        age: 63,
        gender: "male",
        condition: "Chronic heart failure",
      },
      department: "Cardiology",
      reason: "Symptom worsening review",
      visitType: "clinic",
      status: "cancelled",
      cancelledAt: makeDate(-3, 0, 0),
      createdAt: makeDate(-9, 0, 0),
    },
    {
      id: "appt-011",
      confirmationCode: "CVD-2R5S",
      scheduledAt: makeDate(-4, 8, 30),
      patient: {
        id: "pat-111",
        fullName: "Huda Mostafa",
        age: 41,
        gender: "female",
        condition: "Supraventricular tachycardia",
      },
      department: "Cardiology",
      reason: "Palpitation episode follow-up",
      visitType: "clinic",
      status: "completed",
      notes: "SVT episodes reduced in frequency. Continue beta-blockers. Patient educated on vagal maneuvers.",
      createdAt: makeDate(-14, 0, 0),
    },
    {
      id: "appt-012",
      confirmationCode: "CVD-5T8U",
      scheduledAt: makeDate(-5, 16, 0),
      patient: {
        id: "pat-112",
        fullName: "Tariq Nabil",
        age: 70,
        gender: "male",
        condition: "Aortic stenosis",
      },
      department: "Cardiology",
      reason: "Pre-surgical evaluation",
      visitType: "clinic",
      status: "cancelled",
      cancelledAt: makeDate(-6, 0, 0),
      createdAt: makeDate(-15, 0, 0),
    },
  ],
  stats: {
    todayCount: 3,
    upcomingCount: 4,
    completedTodayCount: 0,
    cancelledCount: 2,
  },
}
