import type { QueuePatient, QueueStats } from "./assistantQueue.types"

/* Single-doctor clinic — all patients belong to one doctor */
const DOCTOR_NAME = "Dr. Sarah Khaled"
const DOCTOR_DEPT = "Cardiology"

const today = new Date()
function t(h: number, m = 0) {
  const d = new Date(today)
  d.setHours(h, m, 0, 0)
  return d.toISOString()
}

export const MOCK_QUEUE_PATIENTS: QueuePatient[] = [
  /* ── IN CONSULTATION ─────────────────────────────────── */
  {
    id: "p1",
    queueEntryId: "q1",
    fullName: "Ahmed Hassan",
    age: 58,
    gender: "male",
    condition: "Hypertension follow-up",
    visitType: "follow-up",
    priority: "normal",
    status: "in-consultation",
    scheduledTime: t(9, 0),
    arrivedAt: t(8, 50),
    waitingSince: t(9, 5),
    startedAt: t(9, 40),
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: "101",
    notes: "On Amlodipine 5 mg — reports mild dizziness. Check BP both arms.",
    hasAllergies: true,
    activeMedications: 3,
    vitalAlerts: 1,
    phoneNumber: "+20 100 123 4567",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },

  /* ── WAITING ─────────────────────────────────────────── */
  {
    id: "p3",
    queueEntryId: "q3",
    fullName: "Mohamed Ali Seif",
    age: 62,
    gender: "male",
    condition: "Chest pain evaluation",
    visitType: "urgent-care",
    priority: "urgent",
    status: "waiting",
    scheduledTime: t(10, 0),
    arrivedAt: t(9, 55),
    waitingSince: t(10, 5),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 25,
    roomNumber: null,
    notes: "ECG done in triage — no ST changes. Patient anxious.",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 1,
    phoneNumber: "+20 122 456 7890",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
  {
    id: "p4",
    queueEntryId: "q4",
    fullName: "Layla Ibrahim",
    age: 34,
    gender: "female",
    condition: "Arrhythmia follow-up",
    visitType: "follow-up",
    priority: "normal",
    status: "waiting",
    scheduledTime: t(10, 15),
    arrivedAt: t(10, 10),
    waitingSince: t(10, 20),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: null,
    notes: "Holter monitor results to review today.",
    hasAllergies: true,
    activeMedications: 1,
    vitalAlerts: 0,
    phoneNumber: "+20 155 321 0987",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
  {
    id: "p5",
    queueEntryId: "q5",
    fullName: "Omar Tarek",
    age: 71,
    gender: "male",
    condition: "Heart failure management",
    visitType: "follow-up",
    priority: "urgent",
    status: "waiting",
    scheduledTime: t(10, 30),
    arrivedAt: t(10, 15),
    waitingSince: t(10, 25),
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 35,
    roomNumber: null,
    notes: "Weight gain of 3 kg over last week. Possible fluid retention.",
    hasAllergies: false,
    activeMedications: 6,
    vitalAlerts: 2,
    phoneNumber: "+20 100 654 3210",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },

  /* ── ARRIVED · PREP ──────────────────────────────────── */
  {
    id: "p6",
    queueEntryId: "q6",
    fullName: "Nour Magdy",
    age: 27,
    gender: "female",
    condition: "New patient — palpitations",
    visitType: "new",
    priority: "normal",
    status: "arrived",
    scheduledTime: t(10, 45),
    arrivedAt: t(10, 40),
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 30,
    roomNumber: null,
    notes: "First visit. Referred by GP. No prior cardiac history.",
    hasAllergies: false,
    activeMedications: 0,
    vitalAlerts: 0,
    phoneNumber: "+20 111 222 3344",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
  {
    id: "p7",
    queueEntryId: "q7",
    fullName: "Karim Abdallah",
    age: 55,
    gender: "male",
    condition: "Statin therapy review",
    visitType: "follow-up",
    priority: "normal",
    status: "arrived",
    scheduledTime: t(11, 0),
    arrivedAt: t(10, 55),
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: null,
    notes: "Cholesterol panel done — needs interpretation.",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 122 555 4433",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },

  /* ── SCHEDULED (not arrived yet) ────────────────────── */
  {
    id: "p8",
    queueEntryId: "q8",
    fullName: "Hana Wael",
    age: 48,
    gender: "female",
    condition: "Echo results review",
    visitType: "follow-up",
    priority: "normal",
    status: "scheduled",
    scheduledTime: t(11, 30),
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 25,
    roomNumber: null,
    notes: "Echocardiogram done 3 days ago. EF reportedly 48%.",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 100 111 2222",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
  {
    id: "p9",
    queueEntryId: "q9",
    fullName: "Youssef Ramadan",
    age: 66,
    gender: "male",
    condition: "Cardiac & diabetes co-management",
    visitType: "follow-up",
    priority: "normal",
    status: "scheduled",
    scheduledTime: t(12, 0),
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 30,
    roomNumber: null,
    notes: "HbA1c 8.2 last visit. Metformin 1000 mg BID.",
    hasAllergies: true,
    activeMedications: 4,
    vitalAlerts: 0,
    phoneNumber: "+20 111 333 5566",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
  {
    id: "p10",
    queueEntryId: "q10",
    fullName: "Salma Osman",
    age: 39,
    gender: "female",
    condition: "Syncope episode — walk-in",
    visitType: "walk-in",
    priority: "urgent",
    status: "scheduled",
    scheduledTime: t(12, 30),
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 30,
    roomNumber: null,
    notes: "Walk-in. Reported brief loss of consciousness at home earlier today.",
    hasAllergies: false,
    activeMedications: 0,
    vitalAlerts: 0,
    phoneNumber: "+20 155 888 7766",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },

  /* ── COMPLETED ───────────────────────────────────────── */
  {
    id: "p11",
    queueEntryId: "q11",
    fullName: "Adel Morsy",
    age: 53,
    gender: "male",
    condition: "Blood pressure monitoring",
    visitType: "follow-up",
    priority: "normal",
    status: "completed",
    scheduledTime: t(8, 0),
    arrivedAt: t(7, 55),
    waitingSince: t(8, 10),
    startedAt: t(8, 25),
    completedAt: t(8, 45),
    estimatedDurationMin: 20,
    roomNumber: "101",
    notes: "BP well controlled. Renewed prescription for 3 months.",
    hasAllergies: false,
    activeMedications: 2,
    vitalAlerts: 0,
    phoneNumber: "+20 100 777 8899",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },

  /* ── NO SHOW ─────────────────────────────────────────── */
  {
    id: "p12",
    queueEntryId: "q12",
    fullName: "Bassem Gaber",
    age: 60,
    gender: "male",
    condition: "Annual cardiac checkup",
    visitType: "follow-up",
    priority: "normal",
    status: "no-show",
    scheduledTime: t(8, 30),
    arrivedAt: null,
    waitingSince: null,
    startedAt: null,
    completedAt: null,
    estimatedDurationMin: 20,
    roomNumber: null,
    notes: "Called twice — no answer.",
    hasAllergies: false,
    activeMedications: 1,
    vitalAlerts: 0,
    phoneNumber: "+20 111 000 9988",
    assignedDoctor: DOCTOR_NAME,
    assignedDoctorDepartment: DOCTOR_DEPT,
  },
]

export const MOCK_QUEUE_STATS: QueueStats = {
  totalToday: 11,
  scheduled: 3,
  arrived: 2,
  inWaiting: 3,
  inConsultation: 1,
  completed: 1,
  noShow: 1,
  avgWaitMin: 18,
}
