import type { AppointmentsPageData } from "./appointments.types"
import { partitionAppointmentsByBooking } from "./appointments.utils"

const appointments: AppointmentsPageData["appointments"] = [
  {
    id: "appt-1",
    confirmationCode: "ICV-7829",
    scheduledAt: "2026-04-12T14:30:00Z",
    department: "Cardiology",
    clinician: "Dr. Hossam El-Sayed",
    location: "Downtown Heart Center",
    locationDetail: "Building B, Suite 402",
    status: "no-show",
    notes: "Bring recent ECG results.",
    visitType: "clinic",
  },
  {
    id: "appt-2",
    confirmationCode: "ICV-8912",
    scheduledAt: "2026-04-25T09:00:00Z",
    department: "Nutrition Clinic",
    clinician: "Dr. Mai Ramadan",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 4C",
    status: "no-show",
    visitType: "virtual",
  },
  {
    id: "appt-3",
    confirmationCode: "ICV-3456",
    scheduledAt: "2026-06-10T11:15:00Z",
    department: "General Follow-up",
    clinician: "Dr. Youssef Ibrahim",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 1B",
    status: "upcoming",
    visitType: "clinic",
  },
  {
    id: "appt-4",
    confirmationCode: "ICV-1234",
    scheduledAt: "2026-03-15T10:00:00Z",
    department: "Cardiology",
    clinician: "Dr. Hossam El-Sayed",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 2A",
    status: "completed",
    notes: "ECG normal. Continue current medication.",
    visitType: "clinic",
  },
  {
    id: "appt-5",
    confirmationCode: "ICV-5678",
    scheduledAt: "2026-03-01T09:30:00Z",
    department: "General Follow-up",
    clinician: "Dr. Youssef Ibrahim",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 1B",
    status: "completed",
    visitType: "virtual",
  },
  {
    id: "appt-6",
    confirmationCode: "ICV-9999",
    scheduledAt: "2026-02-20T14:00:00Z",
    department: "Cardiology",
    clinician: "Dr. Hossam El-Sayed",
    location: "Downtown Heart Center",
    locationDetail: "Building B, Suite 402",
    status: "cancelled",
    cancellationReason:
      "Unable to attend due to a family commitment. Patient requested to rebook next month.",
    cancelledBy: "patient",
    cancelledAt: "2026-02-18T09:15:00Z",
    visitType: "clinic",
  },
  {
    id: "appt-7",
    confirmationCode: "ICV-2468",
    scheduledAt: "2026-06-18T16:00:00Z",
    department: "Cardiology",
    clinician: "Dr. Sarah Ahmed",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 3A",
    status: "rescheduled",
    rescheduledTo: "2026-06-18T16:00:00Z",
    visitType: "clinic",
  },
  {
    id: "appt-8",
    confirmationCode: "ICV-1357",
    scheduledAt: "2026-06-05T10:30:00Z",
    department: "Nutrition Clinic",
    clinician: "Dr. Mai Ramadan",
    location: "Virtual Consultation",
    status: "upcoming",
    visitType: "virtual",
  },
  {
    id: "appt-9",
    confirmationCode: "ICV-8642",
    scheduledAt: "2026-06-12T14:45:00Z",
    department: "General Follow-up",
    clinician: "Dr. Youssef Ibrahim",
    location: "ICARE-CVD Main Center",
    locationDetail: "Room 2C",
    status: "upcoming",
    visitType: "clinic",
  },
  {
    id: "appt-10",
    confirmationCode: "ICV-7531",
    scheduledAt: "2026-06-20T09:15:00Z",
    department: "Cardiology",
    clinician: "Dr. Hossam El-Sayed",
    location: "Downtown Heart Center",
    locationDetail: "Building B, Suite 402",
    status: "upcoming",
    visitType: "clinic",
  },
  {
    id: "appt-11",
    confirmationCode: "ICV-9518",
    scheduledAt: "2026-06-28T11:00:00Z",
    department: "Nutrition Clinic",
    clinician: "Dr. Mai Ramadan",
    location: "Virtual Consultation",
    status: "upcoming",
    visitType: "virtual",
  },
]

const { upcoming, past } = partitionAppointmentsByBooking(appointments)

export const mockAppointmentsPage: AppointmentsPageData = {
  doctors: [
    {
      id: "doc-1",
      name: "Dr. Robert Thorne",
      title: "Chief Cardiologist",
      experience: "20+ Years Exp.",
      rating: 4.9,
      specialties: [
        { icon: "heart", label: "Interventional Cardiology", color: "primary" },
        { icon: "activity", label: "Heart Failure", color: "secondary" },
      ],
    },
    {
      id: "doc-2",
      name: "Dr. Sarah Ahmed",
      title: "Senior Cardiologist",
      experience: "15+ Years Exp.",
      rating: 4.8,
      specialties: [
        { icon: "heart", label: "Preventive Cardiology", color: "primary" },
        { icon: "activity", label: "Hypertension", color: "secondary" },
      ],
    },
  ],
  selectedDoctor: {
    id: "doc-1",
    name: "Dr. Robert Thorne",
    title: "Chief Cardiologist",
    experience: "20+ Years Exp.",
    rating: 4.9,
    specialties: [
      { icon: "heart", label: "Interventional Cardiology", color: "primary" },
      { icon: "activity", label: "Heart Failure", color: "secondary" },
    ],
  },
  monthLabel: "October 2023",
  days: [
    { day: "Mon", date: 9, disabled: true, fullDate: "2023-10-09" },
    { day: "Tue", date: 10, fullDate: "2023-10-10" },
    { day: "Wed", date: 11, fullDate: "2023-10-11" },
    { day: "Thu", date: 12, fullDate: "2023-10-12" },
    { day: "Fri", date: 13, fullDate: "2023-10-13" },
  ],
  timeSlotsByDate: {
    "2023-10-09": [
      { time: "09:00 AM", available: true },
      { time: "09:30 AM", available: true, recommended: true, label: "Low wait time" },
      { time: "10:00 AM", available: true },
      { time: "10:30 AM", available: true },
      { time: "11:00 AM", available: false, label: "Booked" },
      { time: "11:30 AM", available: true },
    ],
    "2023-10-10": [
      { time: "09:00 AM", available: true },
      { time: "09:30 AM", available: true, recommended: true, label: "Low wait time" },
      { time: "10:00 AM", available: true },
      { time: "10:30 AM", available: true },
      { time: "11:00 AM", available: false, label: "Booked" },
      { time: "11:30 AM", available: true },
    ],
    "2023-10-11": [
      { time: "09:00 AM", available: true },
      { time: "09:30 AM", available: true, recommended: true, label: "Low wait time" },
      { time: "10:00 AM", available: true },
      { time: "10:30 AM", available: true },
      { time: "11:00 AM", available: false, label: "Booked" },
      { time: "11:30 AM", available: true },
    ],
    "2023-10-12": [
      { time: "09:00 AM", available: true },
      { time: "09:30 AM", available: true, recommended: true, label: "Low wait time" },
      { time: "10:00 AM", available: true },
      { time: "10:30 AM", available: true },
      { time: "11:00 AM", available: false, label: "Booked" },
      { time: "11:30 AM", available: true },
    ],
    "2023-10-13": [
      { time: "09:00 AM", available: true },
      { time: "09:30 AM", available: true, recommended: true, label: "Low wait time" },
      { time: "10:00 AM", available: true },
      { time: "10:30 AM", available: true },
      { time: "11:00 AM", available: false, label: "Booked" },
      { time: "11:30 AM", available: true },
    ],
  },
  appointments,
  upcoming,
  past,
  fees: [
    { label: "Consultation Fee", amount: "$150.00" },
    { label: "Platform Fee", amount: "$5.00" },
    { label: "Insurance Cover", amount: "-$130.00", highlight: true, icon: "shield" },
  ],
  aiTipTitle: "Why this time slot?",
  aiTipBody:
    "Our system analyzed 5,000+ past visits. Tuesdays at 9:30 AM typically have 40% less foot traffic, ensuring you get seen by Dr. Thorne faster.",
}
