import type { AssistantAppointment } from "./assistantAppointments.types"

export const mockAssistantAppointments: AssistantAppointment[] = [
  {
    id: "APT-1001",
    patientName: "Ahmed Ali",
    patientPhone: "+20 101 445 3290",
    patientEmail: "ahmed.ali@example.com",
    doctorName: "Dr. Nada Hassan",
    department: "Cardiology",
    scheduledAt: "2026-04-15T09:30:00.000Z",
    visitType: "clinic",
    reason: "Recurring chest discomfort and dizziness.",
    status: "pending",
  },
  {
    id: "APT-1002",
    patientName: "Mona Sameh",
    patientPhone: "+20 112 900 1142",
    patientEmail: "mona.sameh@example.com",
    doctorName: "Dr. Khaled Emad",
    department: "Hypertension Clinic",
    scheduledAt: "2026-04-15T11:00:00.000Z",
    visitType: "virtual",
    reason: "Blood pressure follow-up and medication review.",
    status: "confirmed",
  },
  {
    id: "APT-1003",
    patientName: "Youssef Mamdouh",
    patientPhone: "+20 100 750 2368",
    patientEmail: "youssef.m@example.com",
    doctorName: "Dr. Mariam Lotfy",
    department: "Arrhythmia Unit",
    scheduledAt: "2026-04-16T08:45:00.000Z",
    visitType: "clinic",
    reason: "Palpitations after exercise.",
    status: "pending",
  },
  {
    id: "APT-1004",
    patientName: "Salma Hegazy",
    patientPhone: "+20 109 772 5531",
    patientEmail: "salma.hegazy@example.com",
    doctorName: "Dr. Omar Saber",
    department: "Preventive Cardiology",
    scheduledAt: "2026-04-14T14:15:00.000Z",
    visitType: "virtual",
    reason: "Review lipid profile and lifestyle plan.",
    status: "completed",
  },
]
