import type { PatientMedicationProfile } from "./assistantMedications.types";

export const MOCK_MEDICATION_PROFILES: PatientMedicationProfile[] = [
  {
    id: "mp1",
    fullName: "Ahmed Hassan",
    age: 62,
    phone: "+20 100 111 2233",
    riskTier: "high",
    overallAdherencePct: 71,
    medications: [
      {
        id: "ml1",
        name: "Metformin",
        strength: "850 mg",
        dosageInstructions: "1 tablet twice daily with meals",
        frequencyLabel: "BID",
        adherencePct7d: 86,
        missedLast7d: 1,
        nextRefillDue: "2026-05-12",
        adherenceHistory7d: [true, true, false, true, true, true, true],
      },
      {
        id: "ml2",
        name: "Atorvastatin",
        strength: "40 mg",
        dosageInstructions: "1 tablet at bedtime",
        frequencyLabel: "HS",
        adherencePct7d: 54,
        missedLast7d: 3,
        nextRefillDue: null,
        adherenceHistory7d: [true, false, false, true, false, true, true],
      },
      {
        id: "ml3",
        name: "Aspirin",
        strength: "81 mg",
        dosageInstructions: "1 tablet daily after breakfast",
        frequencyLabel: "QD",
        adherencePct7d: 92,
        missedLast7d: 0,
        nextRefillDue: "2026-06-01",
        adherenceHistory7d: [true, true, true, true, true, true, true],
      },
    ],
    flags: [
      {
        id: "fl1",
        medicationLineId: "ml2",
        patientId: "mp1",
        reason: "Three missed doses in the last 7 days — confirm tolerance / scheduling.",
        severity: "watch",
        createdAt: "2026-05-04T09:15:00Z",
        createdByLabel: "Assistant",
        status: "open",
      },
    ],
    aiInsights: [
      {
        id: "ai1",
        patientId: "mp1",
        kind: "adherence",
        title: "Evening dose cluster",
        detail:
          "Patient tends to skip HS doses mid-week. Consider SMS nudge Tue–Thu around 9 PM local time.",
        confidencePct: 78,
      },
      {
        id: "ai2",
        patientId: "mp1",
        kind: "refill",
        title: "Statin refill unclear",
        detail: "No refill date on file for atorvastatin — outreach may prevent a gap.",
        confidencePct: 72,
      },
    ],
    contactHistory: [
      {
        id: "ch1",
        patientId: "mp1",
        channel: "sms",
        status: "delivered",
        summary: "Evening statin reminder",
        messagePreview: "Please confirm you are taking your evening medicine as prescribed.",
        createdAt: "2026-05-04T18:30:00Z",
        createdByLabel: "Assistant",
      },
      {
        id: "ch2",
        patientId: "mp1",
        channel: "call",
        status: "replied",
        summary: "Adherence check-in",
        messagePreview: "Patient said bedtime dosing is easy to forget during work shifts.",
        createdAt: "2026-05-02T10:20:00Z",
        createdByLabel: "Mona - Assistant",
      },
    ],
    escalations: [],
  },
  {
    id: "mp2",
    fullName: "Layla Ibrahim",
    age: 54,
    phone: "+20 122 554 8899",
    riskTier: "medium",
    overallAdherencePct: 88,
    medications: [
      {
        id: "ml4",
        name: "Bisoprolol",
        strength: "5 mg",
        dosageInstructions: "1 tablet every morning",
        frequencyLabel: "QD AM",
        adherencePct7d: 88,
        missedLast7d: 1,
        nextRefillDue: "2026-05-20",
        adherenceHistory7d: [true, true, true, false, true, true, true],
      },
      {
        id: "ml5",
        name: "Apixaban",
        strength: "5 mg",
        dosageInstructions: "1 tablet twice daily (≈12 h apart)",
        frequencyLabel: "BID",
        adherencePct7d: 94,
        missedLast7d: 0,
        nextRefillDue: "2026-05-18",
        adherenceHistory7d: [true, true, true, true, true, true, true],
      },
    ],
    flags: [],
    aiInsights: [
      {
        id: "ai3",
        patientId: "mp2",
        kind: "interaction",
        title: "OTC check reminder",
        detail:
          "Patient reported occasional NSAID use — AI suggests reinforcing avoidance without clinician approval.",
        confidencePct: 65,
      },
    ],
    contactHistory: [
      {
        id: "ch3",
        patientId: "mp2",
        channel: "push",
        status: "delivered",
        summary: "OTC safety reminder",
        messagePreview: "Please check with your cardiology team before using pain medicines.",
        createdAt: "2026-05-03T11:15:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [],
  },
  {
    id: "mp3",
    fullName: "Omar Tarek",
    age: 71,
    phone: null,
    riskTier: "high",
    overallAdherencePct: 62,
    medications: [
      {
        id: "ml6",
        name: "Furosemide",
        strength: "40 mg",
        dosageInstructions: "1 tablet every morning; weigh daily",
        frequencyLabel: "QD AM",
        adherencePct7d: 58,
        missedLast7d: 2,
        nextRefillDue: "2026-05-08",
        adherenceHistory7d: [true, false, true, true, false, true, true],
      },
      {
        id: "ml7",
        name: "Spironolactone",
        strength: "25 mg",
        dosageInstructions: "1 tablet daily with food",
        frequencyLabel: "QD",
        adherencePct7d: 66,
        missedLast7d: 2,
        nextRefillDue: "2026-05-09",
        adherenceHistory7d: [false, true, true, false, true, true, true],
      },
    ],
    flags: [
      {
        id: "fl2",
        medicationLineId: "ml6",
        patientId: "mp3",
        reason: "HF regimen — missed doses + rising weight in chart note.",
        severity: "critical",
        createdAt: "2026-05-03T14:00:00Z",
        createdByLabel: "Assistant",
        status: "open",
      },
    ],
    aiInsights: [
      {
        id: "ai4",
        patientId: "mp3",
        kind: "education",
        title: "Diuretic timing",
        detail:
          "Short educational SMS on morning dosing may improve consistency for loop diuretics.",
        confidencePct: 81,
      },
    ],
    contactHistory: [
      {
        id: "ch4",
        patientId: "mp3",
        channel: "sms",
        status: "failed",
        summary: "Diuretic refill reminder",
        messagePreview: "Your heart medication refill may be due soon. Please contact the clinic.",
        createdAt: "2026-05-04T08:45:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [
      {
        id: "esc1",
        patientId: "mp3",
        medicationLineId: "ml6",
        priority: "critical",
        reason: "Missed diuretic doses with high-risk HF profile.",
        note: "Please review whether the care team should call today.",
        status: "waiting_review",
        createdAt: "2026-05-03T14:10:00Z",
        createdByLabel: "Assistant",
      },
    ],
  },
  {
    id: "mp4",
    fullName: "Sara Mahmoud",
    age: 48,
    phone: "+20 111 882 3344",
    riskTier: "low",
    overallAdherencePct: 92,
    medications: [
      {
        id: "ml8",
        name: "Ramipril",
        strength: "5 mg",
        dosageInstructions: "1 capsule each morning",
        frequencyLabel: "QD AM",
        adherencePct7d: 94,
        missedLast7d: 0,
        nextRefillDue: "2026-05-25",
        adherenceHistory7d: [true, true, true, true, true, true, true],
      },
      {
        id: "ml9",
        name: "Empagliflozin",
        strength: "10 mg",
        dosageInstructions: "1 tablet once daily with breakfast",
        frequencyLabel: "QD",
        adherencePct7d: 89,
        missedLast7d: 1,
        nextRefillDue: "2026-05-22",
        adherenceHistory7d: [true, true, false, true, true, true, true],
      },
    ],
    flags: [],
    aiInsights: [
      {
        id: "ai5",
        patientId: "mp4",
        kind: "refill",
        title: "Sync refill dates",
        detail: "ACE inhibitor and SGLT2 renewals are 3 days apart — bundle pickup may help adherence.",
        confidencePct: 70,
      },
    ],
    contactHistory: [
      {
        id: "ch5",
        patientId: "mp4",
        channel: "sms",
        status: "delivered",
        summary: "Morning BP meds reminder",
        messagePreview: "Remember your ramipril with breakfast today.",
        createdAt: "2026-05-05T07:05:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [],
  },
  {
    id: "mp5",
    fullName: "Karim Adel",
    age: 59,
    phone: "+20 128 901 7722",
    riskTier: "medium",
    overallAdherencePct: 76,
    medications: [
      {
        id: "ml10",
        name: "Clopidogrel",
        strength: "75 mg",
        dosageInstructions: "1 tablet daily at the same time",
        frequencyLabel: "QD",
        adherencePct7d: 62,
        missedLast7d: 2,
        nextRefillDue: "2026-05-14",
        adherenceHistory7d: [true, false, true, true, false, true, true],
      },
      {
        id: "ml11",
        name: "Metoprolol succinate",
        strength: "47.5 mg",
        dosageInstructions: "1 tablet every morning",
        frequencyLabel: "QD AM",
        adherencePct7d: 81,
        missedLast7d: 1,
        nextRefillDue: "2026-05-30",
        adherenceHistory7d: [true, true, true, true, false, true, true],
      },
    ],
    flags: [
      {
        id: "fl3",
        medicationLineId: "ml10",
        patientId: "mp5",
        reason: "Antiplatelet gaps noted — verify bleeding concerns vs intentional skips.",
        severity: "watch",
        createdAt: "2026-05-04T11:40:00Z",
        createdByLabel: "Assistant",
        status: "open",
      },
    ],
    aiInsights: [
      {
        id: "ai6",
        patientId: "mp5",
        kind: "adherence",
        title: "Weekend skip pattern",
        detail: "Missed clopidogrel doses cluster on Fri–Sat; trial weekend SMS at fixed clock time.",
        confidencePct: 74,
      },
      {
        id: "ai7",
        patientId: "mp5",
        kind: "education",
        title: "Beta-blocker consistency",
        detail: "Morning metoprolol adherence strong; reinforce linking clopidogrel to same routine.",
        confidencePct: 68,
      },
    ],
    contactHistory: [
      {
        id: "ch6",
        patientId: "mp5",
        channel: "push",
        status: "queued",
        summary: "Dual antithrombotic safety tip",
        messagePreview: "Do not stop clopidogrel without calling the clinic.",
        createdAt: "2026-05-05T09:00:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [],
  },
  {
    id: "mp6",
    fullName: "Nour El-Din",
    age: 67,
    phone: "+20 100 445 9011",
    riskTier: "high",
    overallAdherencePct: 58,
    medications: [
      {
        id: "ml12",
        name: "Warfarin",
        strength: "5 mg",
        dosageInstructions: "Take exactly as directed by INR clinic — same time daily",
        frequencyLabel: "QD",
        adherencePct7d: 52,
        missedLast7d: 3,
        nextRefillDue: "2026-05-11",
        adherenceHistory7d: [false, true, false, true, true, false, true],
      },
      {
        id: "ml13",
        name: "Digoxin",
        strength: "0.125 mg",
        dosageInstructions: "1 tablet daily; report palpitations or nausea",
        frequencyLabel: "QD",
        adherencePct7d: 64,
        missedLast7d: 2,
        nextRefillDue: null,
        adherenceHistory7d: [true, true, false, false, true, true, true],
      },
    ],
    flags: [
      {
        id: "fl4",
        medicationLineId: "ml12",
        patientId: "mp6",
        reason: "Variable warfarin intake — INR stability risk.",
        severity: "critical",
        createdAt: "2026-05-03T16:20:00Z",
        createdByLabel: "Assistant",
        status: "open",
      },
      {
        id: "fl5",
        medicationLineId: "ml13",
        patientId: "mp6",
        reason: "Digoxin without documented refill — possible adherence gap.",
        severity: "watch",
        createdAt: "2026-05-04T08:10:00Z",
        createdByLabel: "Assistant",
        status: "open",
      },
    ],
    aiInsights: [
      {
        id: "ai8",
        patientId: "mp6",
        kind: "interaction",
        title: "Polypharmacy watch",
        detail: "Digoxin + diuretic history in chart — AI flags electrolyte teaching opportunity.",
        confidencePct: 77,
      },
    ],
    contactHistory: [
      {
        id: "ch7",
        patientId: "mp6",
        channel: "call",
        status: "delivered",
        summary: "INR clinic coordination",
        messagePreview: "Confirmed next lab draw Thursday AM fasting.",
        createdAt: "2026-05-02T14:30:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [],
  },
  {
    id: "mp7",
    fullName: "Yasmine Farouk",
    age: 41,
    phone: null,
    riskTier: "low",
    overallAdherencePct: 95,
    medications: [
      {
        id: "ml14",
        name: "Rosuvastatin",
        strength: "10 mg",
        dosageInstructions: "1 tablet every evening",
        frequencyLabel: "HS",
        adherencePct7d: 97,
        missedLast7d: 0,
        nextRefillDue: "2026-06-10",
        adherenceHistory7d: [true, true, true, true, true, true, true],
      },
    ],
    flags: [],
    aiInsights: [],
    contactHistory: [
      {
        id: "ch8",
        patientId: "mp7",
        channel: "sms",
        status: "delivered",
        summary: "Statin tolerance check-in",
        messagePreview: "Any muscle aches since starting rosuvastatin? Reply YES or NO.",
        createdAt: "2026-05-01T12:00:00Z",
        createdByLabel: "Assistant",
      },
    ],
    escalations: [],
  },
];
