import type { ProcedureOrder, ProcedureStats } from "./assistantProcedures.types"

export const mockProcedureOrders: ProcedureOrder[] = [
  {
    id: "proc-001",
    patientId: "pt-101",
    patientName: "Sara Ahmed",
    patientAge: 54,
    patientPhone: "+20 100 123 4567",
    doctorName: "Dr. Mahmoud Ali",
    department: "Cardiology",
    procedureName: "Cardiac Catheterization",
    scheduledAt: "2026-05-10T09:00:00Z",
    status: "in-progress",
    priority: "urgent",
    notes: "Patient is on blood thinners. Ensure all pre-procedure labs are collected at least 24h before.",
    createdAt: "2026-05-04T08:00:00Z",
    requirements: [
      {
        id: "req-001-1",
        title: "CBC & Coagulation panel",
        description: "Full blood count + PT/INR/aPTT",
        allowsAttachment: true,
        isDone: true,
        completedAt: "2026-05-04T10:30:00Z",
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-001-2",
        title: "Signed consent form",
        description: "Patient must sign the procedure consent form",
        allowsAttachment: true,
        isDone: true,
        completedAt: "2026-05-04T11:00:00Z",
        attachmentUrl: "/uploads/consent-sara-ahmed.pdf",
        attachmentName: "consent-sara-ahmed.pdf",
      },
      {
        id: "req-001-3",
        title: "Fasting confirmation (6h NPO)",
        description: "Confirm patient has been fasting for at least 6 hours",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-001-4",
        title: "IV access established",
        description: "18G or larger IV cannula in right antecubital fossa",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-001-5",
        title: "Insurance pre-authorization",
        description: "Submit and receive approval from insurer",
        allowsAttachment: true,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
    ],
  },
  {
    id: "proc-002",
    patientId: "pt-102",
    patientName: "Omar Hassan",
    patientAge: 67,
    patientPhone: "+20 111 987 6543",
    doctorName: "Dr. Hana Farid",
    department: "Cardiology",
    procedureName: "Echocardiogram (TEE)",
    scheduledAt: "2026-05-12T11:30:00Z",
    status: "pending",
    priority: "normal",
    notes: null,
    createdAt: "2026-05-04T09:15:00Z",
    requirements: [
      {
        id: "req-002-1",
        title: "NPO for 4 hours prior",
        description: "Patient must not eat or drink for 4 hours before the TEE",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-002-2",
        title: "Throat spray consent",
        description: "Confirm patient understands use of topical anesthetic",
        allowsAttachment: true,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-002-3",
        title: "Denture / dental removal",
        description: "Check that patient has removed any dental appliances",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
    ],
  },
  {
    id: "proc-003",
    patientId: "pt-103",
    patientName: "Nadia Kamal",
    patientAge: 45,
    patientPhone: "+20 122 555 0011",
    doctorName: "Dr. Mahmoud Ali",
    department: "Cardiology",
    procedureName: "Pacemaker Implantation",
    scheduledAt: "2026-05-08T08:00:00Z",
    status: "completed",
    priority: "emergency",
    notes: "High-risk patient. Anaesthesia team on standby.",
    createdAt: "2026-05-03T14:00:00Z",
    requirements: [
      {
        id: "req-003-1",
        title: "Pre-op blood work",
        description: "BMP, CBC, coagulation, type & screen",
        allowsAttachment: true,
        isDone: true,
        completedAt: "2026-05-03T16:00:00Z",
        attachmentUrl: "/uploads/labs-nadia-preop.pdf",
        attachmentName: "labs-nadia-preop.pdf",
      },
      {
        id: "req-003-2",
        title: "Chest X-ray",
        description: "PA and lateral views",
        allowsAttachment: true,
        isDone: true,
        completedAt: "2026-05-03T17:30:00Z",
        attachmentUrl: "/uploads/cxr-nadia.pdf",
        attachmentName: "cxr-nadia.pdf",
      },
      {
        id: "req-003-3",
        title: "Informed consent signed",
        description: null,
        allowsAttachment: true,
        isDone: true,
        completedAt: "2026-05-04T08:00:00Z",
        attachmentUrl: "/uploads/consent-nadia-pm.pdf",
        attachmentName: "consent-nadia-pm.pdf",
      },
      {
        id: "req-003-4",
        title: "Antibiotics administered",
        description: "1g cefazolin IV 30 min before incision",
        allowsAttachment: false,
        isDone: true,
        completedAt: "2026-05-08T07:30:00Z",
        attachmentUrl: null,
        attachmentName: null,
      },
    ],
  },
  {
    id: "proc-004",
    patientId: "pt-104",
    patientName: "Youssef Ibrahim",
    patientAge: 72,
    patientPhone: null,
    doctorName: "Dr. Hana Farid",
    department: "Cardiology",
    procedureName: "Coronary Angioplasty (PCI)",
    scheduledAt: "2026-05-14T10:00:00Z",
    status: "pending",
    priority: "urgent",
    notes: "Patient is allergic to iodine-based contrast — use iso-osmolar alternative.",
    createdAt: "2026-05-04T11:00:00Z",
    requirements: [
      {
        id: "req-004-1",
        title: "Allergy alert documented",
        description: "Iodine contrast allergy noted in chart and wristband",
        allowsAttachment: false,
        isDone: true,
        completedAt: "2026-05-04T11:30:00Z",
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-004-2",
        title: "Renal function panel",
        description: "Creatinine & eGFR required before contrast use",
        allowsAttachment: true,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-004-3",
        title: "Dual antiplatelet loaded",
        description: "Aspirin 325mg + Clopidogrel 600mg loading dose",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
      {
        id: "req-004-4",
        title: "Patient transport arranged",
        description: "Wheelchair / stretcher booked for cath lab transfer",
        allowsAttachment: false,
        isDone: false,
        completedAt: null,
        attachmentUrl: null,
        attachmentName: null,
      },
    ],
  },
]

export const mockProcedureStats: ProcedureStats = {
  total: mockProcedureOrders.length,
  pending: mockProcedureOrders.filter((o) => o.status === "pending").length,
  inProgress: mockProcedureOrders.filter((o) => o.status === "in-progress").length,
  completed: mockProcedureOrders.filter((o) => o.status === "completed").length,
}
