import type { DoctorProfile } from "./assistantDoctors.types"

export const MOCK_DOCTORS: DoctorProfile[] = [
  {
    id: "1",
    name: "Dr. Sarah Jenkins",
    specialty: "Senior Cardiologist",
    status: "in-consultation",
    patientsWaiting: 5,
    loadLevel: "high",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahJenkins",
    room: "Room 302",
    estTimeRemainingMins: 12,
    avgWaitTimeMins: 35,
    shiftStart: "08:00 AM",
    shiftEnd: "04:00 PM",
    patientsSeen: 14,
    totalPatients: 24,
    tags: ["English", "Echocardiography"],
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Heart Failure Specialist",
    status: "available",
    patientsWaiting: 1,
    loadLevel: "optimal",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=MichaelChen",
    room: "Room 205",
    avgWaitTimeMins: 10,
    shiftStart: "09:00 AM",
    shiftEnd: "05:00 PM",
    patientsSeen: 8,
    totalPatients: 18,
    tags: ["Mandarin", "Transplant"],
  },
  {
    id: "3",
    name: "Dr. Elena Rodriguez",
    specialty: "Electrophysiology Expert",
    status: "in-consultation",
    patientsWaiting: 3,
    loadLevel: "moderate",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ElenaRodriguez",
    room: "Lab B",
    estTimeRemainingMins: 25,
    avgWaitTimeMins: 20,
    shiftStart: "07:30 AM",
    shiftEnd: "03:30 PM",
    patientsSeen: 10,
    totalPatients: 15,
    tags: ["Spanish", "Ablation"],
  },
  {
    id: "4",
    name: "Dr. Alistair Cook",
    specialty: "Pediatric Cardiology",
    status: "away",
    patientsWaiting: 0,
    loadLevel: "inactive",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=AlistairCook",
    room: "East Wing",
    shiftStart: "Off",
    shiftEnd: "Off",
    patientsSeen: 0,
    totalPatients: 0,
    tags: ["Pediatrics", "Congenital"],
  },
  {
    id: "5",
    name: "Dr. James Wilson",
    specialty: "Vascular Surgery",
    status: "available",
    patientsWaiting: 2,
    loadLevel: "optimal",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=JamesWilson",
    room: "OR 4",
    avgWaitTimeMins: 15,
    shiftStart: "08:00 AM",
    shiftEnd: "06:00 PM",
    patientsSeen: 6,
    totalPatients: 12,
    tags: ["Surgery", "Endovascular"],
  },
  {
    id: "6",
    name: "Dr. Amara Okoro",
    specialty: "Cardiac Imaging",
    status: "in-consultation",
    patientsWaiting: 4,
    loadLevel: "moderate",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=AmaraOkoro",
    room: "MRI Room 1",
    estTimeRemainingMins: 8,
    avgWaitTimeMins: 22,
    shiftStart: "09:00 AM",
    shiftEnd: "05:00 PM",
    patientsSeen: 18,
    totalPatients: 25,
    tags: ["MRI", "CT Scan"],
  },
  {
    id: "7",
    name: "Dr. Sophia Patel",
    specialty: "Preventative Cardiology",
    status: "available",
    patientsWaiting: 2,
    loadLevel: "optimal",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SophiaPatel",
    room: "Room 110",
    avgWaitTimeMins: 12,
    shiftStart: "10:00 AM",
    shiftEnd: "04:00 PM",
    patientsSeen: 4,
    totalPatients: 14,
    tags: ["Hindi", "Nutrition"],
  },
]
