/** Default empty state for extended HPI fields (3C–3M) merged into `medical` step. */
export const MEDICAL_HPI_EXTENDED_DEFAULTS = {
  palpitationsOnsetType: "",
  palpitationsDuration: "",
  palpitationsRhythm: "",
  palpitationsRate: "",
  palpitationsTriggers: [] as string[],
  palpitationsTermination: "",
  palpitationsAssociated: [] as string[],
  syncopeCircumstances: [] as string[],
  syncopeProdrome: [] as string[],
  syncopeLocDuration: "",
  syncopeRecovery: "",
  syncopeInjury: "",
  syncopePreviousSimilar: "",
  syncopePreviousCount: "",
  syncopeFamilySuddenDeath: "",
  edemaLocation: [] as string[],
  edemaSymmetry: "",
  edemaSide: "",
  edemaDiurnal: "",
  edemaWeightGain: "",
  edemaWeightGainKg: "",
  edemaDiureticResponse: "",
  fatigueNYHA: "",
  fatigueOnset: "",
  fatigueAssociated: [] as string[],
  constitFever: "",
  constitFeverOnsetDate: "",
  constitFeverPattern: "",
  constitChills: "",
  constitNightSweats: "",
  constitWeightLoss: "",
  constitWeightLossAmount: "",
  constitWeightLossTimeframe: "",
  constitFatigue: "",
  pvClaudication: "",
  pvSite: [] as string[],
  pvDistanceMeters: "",
  pvReliefRest: "",
  pvProgression: "",
  pvRestPain: "",
  pvUlcers: "",
  pvColdExtremities: "",
  hepaticDistension: "",
  hepaticEpigastric: "",
  hepaticNausea: "",
  hepaticAppetite: "",
  jaundiceOnsetDate: "",
  jaundiceCourse: "",
  jaundiceDarkUrine: "",
  jaundicePaleStools: "",
  jaundicePruritus: "",
  cyanosisType: [] as string[],
  cyanosisTiming: "",
  cyanosisOnset: "",
  embLimbPain: "",
  embVisualLoss: "",
  embFlankPain: "",
  embAbdominalPain: "",
  embTIA: "",
  embStroke: "",
  neuroDizziness: "",
  neuroSyncope: "",
  neuroWeakness: "",
  neuroSpeech: "",
  neuroVisual: "",
  neuroConfusion: "",
} as const;
