import type { PatientDashboardData } from "./dashboard.types"

export const mockPatientDashboard: PatientDashboardData = {
  patient: {
    id: "PT-1842",
    fullName: "Sara Ahmed",
    age: 29,
  },
  lastVitalsAt: "2026-04-02T09:30:00Z",
  vitals: [
    {
      id: "heart_rate",
      label: "Heart Rate",
      value: "78",
      unit: "bpm",
      reference: "60–100",
      lastMeasuredAt: "2026-04-02T09:30:00Z",
    },
    {
      id: "blood_pressure",
      label: "Blood Pressure",
      value: "118/76",
      reference: "< 120/80",
      lastMeasuredAt: "2026-04-02T09:30:00Z",
    },
    {
      id: "spo2",
      label: "SpO₂",
      value: "98",
      unit: "%",
      reference: "95–100",
      lastMeasuredAt: "2026-04-02T09:30:00Z",
    },
    {
      id: "temperature",
      label: "Temperature",
      value: "36.7",
      unit: "°C",
      reference: "36.1–37.2",
      lastMeasuredAt: "2026-04-02T09:30:00Z",
    },
  ],
  upcomingAppointments: [
    {
      id: "appt-1",
      scheduledAt: "2026-04-12T14:30:00Z",
      department: "Cardiology",
      clinician: "Dr. Hossam El-Sayed",
      location: "ICARE-CVD Main Center (Room 2A)",
      status: "confirmed",
    },
    {
      id: "appt-2",
      scheduledAt: "2026-04-25T09:00:00Z",
      department: "Nutrition Clinic",
      clinician: "Dr. Mai Ramadan",
      location: "ICARE-CVD Main Center (Room 4C)",
      status: "scheduled",
    },
    {
      id: "appt-3",
      scheduledAt: "2026-05-02T11:15:00Z",
      department: "General Follow-up",
      clinician: "Dr. Youssef Ibrahim",
      location: "ICARE-CVD Main Center (Room 1B)",
      status: "scheduled",
    },
  ],
  medications: [
    {
      id: "med-1",
      name: "Aspirin",
      dosage: "75 mg",
      frequency: "Once daily",
      timeOfDay: "Morning",
      lastTakenAt: "2026-04-14T08:14:00Z",
      status: "taken",
      adherenceHistory: [true, true, true, true, true, true, true],
    },
    {
      id: "med-2",
      name: "Metoprolol",
      dosage: "50 mg",
      frequency: "Twice daily",
      timeOfDay: "Morning",
      lastTakenAt: "2026-04-14T08:16:00Z",
      status: "taken",
      adherenceHistory: [true, false, true, false, true, true, true],
    },
    {
      id: "med-3",
      name: "Atorvastatin",
      dosage: "20 mg",
      frequency: "Once daily",
      timeOfDay: "Evening",
      status: "due",
      adherenceHistory: [true, true, true, true, true, true, true],
      dueAt: "2026-04-14T21:00:00Z",
    },
    {
      id: "med-4",
      name: "Metoprolol",
      dosage: "50 mg",
      frequency: "Twice daily",
      timeOfDay: "Evening",
      status: "missed",
      adherenceHistory: [true, true, true, true, true, true, false],
      lastTakenAt: "2026-04-13T21:00:00Z",
      dueAt: "2026-04-14T21:00:00Z",
    },
  ],
  careSummary: {
    lastCheckUpAt: "2026-04-02T09:30:00Z",
    nextFollowUpAt: "2026-04-12T14:30:00Z",
    planNote:
      "Keep monitoring vitals at home. Bring recent measurements to your next appointment for better adjustments.",
  },
}
