"use client"

import { useCallback, useRef, useState } from "react"
import { cn } from "@/lib/utils"
import type { LucideIcon } from "lucide-react"
import {
  ActivityIcon,
  BarChart2Icon,
  BoxIcon,
  BrainCircuitIcon,
  CheckCircle2Icon,
  ClockIcon,
  FileIcon,
  FilmIcon,
  HeartPulseIcon,
  LayersIcon,
  LayoutGridIcon,
  Loader2Icon,
  MoveIcon,
  ScanHeartIcon,
  SparklesIcon,
  SplitIcon,
  Trash2Icon,
  TrendingUpIcon,
  UploadCloudIcon,
  XCircleIcon,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { CineMRIAiChatDialog } from "./CineMRIAiChatDialog"
import { MriPlotlyChart } from "./MriPlotlyChart"

// ─── types ────────────────────────────────────────────────────────────────────

type AnalysisStatus = "idle" | "processing" | "done" | "error"

export type MriDiagnosisClass = "NOR" | "HCM" | "DCM" | "MINF" | "RV"

export interface MriClinicalFeatures {
  ed_vol_lv: number
  es_vol_lv: number
  ed_vol_rv: number
  es_vol_rv: number
  ed_mass_myo: number
  es_vol_myo: number
  ef_lv: number
  ef_rv: number
  ed_ratio_lv_rv: number
  es_ratio_lv_rv: number
  ed_ratio_myo_lv: number
  es_ratio_myo_lv: number
  es_max_mean_mwt: number
  es_stdev_mean_mwt: number
  es_mean_stdev_mwt: number
  es_stdev_stdev_mwt: number
  ed_max_mean_mwt: number
  ed_stdev_mean_mwt: number
  ed_mean_stdev_mwt: number
  ed_stdev_stdev_mwt: number
}

export interface MriResult {
  diagnosisClass: MriDiagnosisClass
  clinicalFeatures: MriClinicalFeatures
  elapsedSec: number
  // Visualizations — base64 images generated by the ML service
  rawGifB64?: string           // display_video()         — raw cine loop (grayscale)
  segGifB64?: string           // build_seg_gif()         — segmentation overlay animation (ED ↔ ES)
  segGridEdB64?: string        // display_seg_grid(ED)    — per-slice ED mask grid
  segGridEsB64?: string        // display_seg_grid(ES)    — per-slice ES mask grid
  meanSignalChartJson?: unknown // plot_mean_signal()      — interactive line chart (Plotly)
  overviewImgB64?: string      // display_overview()      — 4-row comparison grid
  histogramImgB64?: string     // plot_intensity_histogram() — ED vs ES voxel histograms
  thickeningChartJson?: unknown // plot_thickening_map()  — interactive bar chart (Plotly)
  wallMotionChartJson?: unknown // plot_wall_motion()    — interactive line chart (Plotly)
  rendering3dJson?: unknown    // display_3d_rendering()  — interactive 3D scatter (Plotly)
  mprImgB64?: string           // display_mpr()           — Axial / Sagittal / Coronal views
}

// ─── service URL ─────────────────────────────────────────────────────────────

const MRI_URL =
  typeof window !== "undefined"
    ? (process.env.NEXT_PUBLIC_MRI_SERVICE_URL ?? "http://localhost:8090")
    : "http://localhost:8090"

// ─── constants ────────────────────────────────────────────────────────────────

const DIAGNOSIS_CONFIG: Record<
  MriDiagnosisClass,
  { label: string; description: string; badge: string; text: string; bg: string; border: string; dot: string }
> = {
  NOR: {
    label: "Normal",
    description: "No significant structural or functional cardiac abnormality detected.",
    badge: "bg-emerald-100 text-emerald-700",
    text: "text-emerald-800",
    bg: "bg-emerald-50/60",
    border: "border-emerald-200",
    dot: "bg-emerald-400",
  },
  HCM: {
    label: "Hypertrophic Cardiomyopathy",
    description: "Abnormal thickening of the myocardial wall, typically affecting the interventricular septum.",
    badge: "bg-amber-100 text-amber-700",
    text: "text-amber-800",
    bg: "bg-amber-50/60",
    border: "border-amber-200",
    dot: "bg-amber-400",
  },
  DCM: {
    label: "Dilated Cardiomyopathy",
    description: "Enlarged, weakened left ventricle with significantly reduced ejection fraction.",
    badge: "bg-orange-100 text-orange-700",
    text: "text-orange-800",
    bg: "bg-orange-50/60",
    border: "border-orange-200",
    dot: "bg-orange-400",
  },
  MINF: {
    label: "Myocardial Infarction",
    description: "Evidence of regional wall motion abnormality consistent with prior myocardial infarction.",
    badge: "bg-red-100 text-red-700",
    text: "text-red-800",
    bg: "bg-red-50/60",
    border: "border-red-200",
    dot: "bg-red-400",
  },
  RV: {
    label: "Right Ventricular Disease",
    description: "Abnormal right ventricular size or function relative to the left ventricle.",
    badge: "bg-violet-100 text-violet-700",
    text: "text-violet-800",
    bg: "bg-violet-50/60",
    border: "border-violet-200",
    dot: "bg-violet-400",
  },
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatElapsed(sec: number): string {
  if (sec < 60) return `${sec}s`
  return `${Math.floor(sec / 60)}m ${sec % 60}s`
}

function fmt(n: number, decimals = 1): string {
  return n.toFixed(decimals)
}

// ─── sub-components ───────────────────────────────────────────────────────────

function MriDropZone({
  phase,
  onFileSelected,
}: {
  phase: "ED" | "ES"
  onFileSelected: (file: File) => void
}) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [isDragging, setIsDragging] = useState(false)

  const handleFiles = useCallback(
    (files: FileList | null) => {
      if (!files?.length) return
      const file = files[0]
      if (!file.name.endsWith(".nii") && !file.name.endsWith(".nii.gz")) return
      onFileSelected(file)
    },
    [onFileSelected],
  )

  const phaseLabel = phase === "ED" ? "End-Diastolic (ED)" : "End-Systolic (ES)"
  const phaseColor = phase === "ED" ? "text-blue-600" : "text-violet-600"
  const phaseBg = phase === "ED" ? "bg-blue-50" : "bg-violet-50"

  return (
    <div
      role="button"
      tabIndex={0}
      aria-label={`Upload ${phaseLabel} NIfTI scan`}
      onClick={() => inputRef.current?.click()}
      onKeyDown={(e) => e.key === "Enter" && inputRef.current?.click()}
      onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
      onDragLeave={() => setIsDragging(false)}
      onDrop={(e) => {
        e.preventDefault()
        setIsDragging(false)
        handleFiles(e.dataTransfer.files)
      }}
      className={cn(
        "flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed py-6 transition-colors",
        isDragging
          ? "border-[#1A5345]/50 bg-[#F0F7F4]"
          : "border-[#E5EEEA] bg-[#FAFAF8] hover:border-[#1A5345]/30 hover:bg-[#F6FBF9]",
      )}
    >
      <div className={cn("rounded-full px-2.5 py-0.5 text-[10px] font-bold tracking-wide", phaseBg, phaseColor)}>
        {phase}
      </div>
      <div className={cn(
        "flex size-9 items-center justify-center rounded-full transition-colors",
        isDragging ? "bg-[#1A5345]/10" : "bg-[#E8F0EE]",
      )}>
        <UploadCloudIcon className={cn("size-4", isDragging ? "text-[#1A5345]" : "text-[#2C6A5B]")} />
      </div>
      <div className="text-center">
        <p className="text-[11px] font-medium text-[#102F27]">
          {phaseLabel}
        </p>
        <p className="mt-0.5 text-[10px] text-muted-foreground">
          Drop or{" "}
          <span className="text-[#1A5345] underline underline-offset-2">browse</span>
          {" "}· .nii / .nii.gz
        </p>
      </div>
      <input
        ref={inputRef}
        type="file"
        accept=".nii,.nii.gz"
        className="sr-only"
        onChange={(e) => handleFiles(e.target.files)}
      />
    </div>
  )
}

function MriFileCard({
  file,
  phase,
  status,
  elapsed,
  onRemove,
}: {
  file: File
  phase: "ED" | "ES"
  status: AnalysisStatus
  elapsed: number
  onRemove: () => void
}) {
  const phaseColor = phase === "ED" ? "text-blue-600 bg-blue-50" : "text-violet-600 bg-violet-50"

  const statusMap = {
    idle:       { badge: "",                                icon: null,             label: "" },
    processing: { badge: "bg-amber-50 text-amber-700",     icon: Loader2Icon,      label: "Analyzing…" },
    done:       { badge: "bg-emerald-50 text-emerald-700", icon: CheckCircle2Icon, label: "Done" },
    error:      { badge: "bg-red-50 text-red-600",         icon: XCircleIcon,      label: "Failed" },
  }
  const cfg = statusMap[status]
  const Icon = cfg.icon

  return (
    <div className="rounded-lg border border-[#E5EEEA] bg-white p-3">
      <div className="flex items-center gap-3">
        <div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-[#EEF5F3]">
          <FileIcon className="size-4 text-[#1A5345]" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className={cn("rounded px-1.5 py-0.5 text-[9px] font-bold", phaseColor)}>{phase}</span>
            <p className="truncate text-[12px] font-semibold text-[#102F27]">{file.name}</p>
          </div>
          <div className="mt-0.5 flex flex-wrap items-center gap-2">
            <span className="text-[10px] text-muted-foreground">{formatBytes(file.size)}</span>
            {Icon && (
              <span className={cn("flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[10px] font-medium", cfg.badge)}>
                <Icon className={cn("size-2.5", status === "processing" && "animate-spin")} />
                {cfg.label}
              </span>
            )}
            {status === "processing" && elapsed > 0 && (
              <span className="flex items-center gap-1 text-[10px] text-muted-foreground">
                <ClockIcon className="size-2.5" />
                {formatElapsed(elapsed)}
              </span>
            )}
          </div>
        </div>
        <Button
          size="sm"
          variant="ghost"
          disabled={status === "processing"}
          className="h-6 w-6 shrink-0 p-0 text-[#6B7870] hover:bg-red-50 hover:text-red-500"
          onClick={onRemove}
        >
          <Trash2Icon className="size-3.5" />
        </Button>
      </div>
    </div>
  )
}

function DiagnosisClassCard({ diagnosisClass }: { diagnosisClass: MriDiagnosisClass }) {
  const cfg = DIAGNOSIS_CONFIG[diagnosisClass]

  return (
    <div className={cn("rounded-xl border-2 p-4", cfg.bg, cfg.border)}>
      <div className="flex items-center gap-3">
        <div className={cn("flex size-10 shrink-0 items-center justify-center rounded-xl border-2", cfg.border, "bg-white")}>
          <HeartPulseIcon className={cn("size-5", cfg.text)} />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className={cn("rounded-full px-2.5 py-0.5 text-[11px] font-bold tracking-wide", cfg.badge)}>
              {diagnosisClass}
            </span>
            <p className={cn("text-[13px] font-bold", cfg.text)}>{cfg.label}</p>
          </div>
          <p className="mt-1 text-[11px] text-[#102F27]/70">{cfg.description}</p>
        </div>
        <CheckCircle2Icon className={cn("size-5 shrink-0", cfg.text)} />
      </div>
    </div>
  )
}

function KeyMetricsGrid({ features }: { features: MriClinicalFeatures }) {
  const metrics = [
    {
      label: "EF (LV)",
      value: `${fmt(features.ef_lv)} %`,
      sub: "Left ventricular ejection fraction",
      color: features.ef_lv < 40 ? "text-red-700" : features.ef_lv < 55 ? "text-amber-700" : "text-emerald-700",
      bg: features.ef_lv < 40 ? "bg-red-50" : features.ef_lv < 55 ? "bg-amber-50" : "bg-emerald-50",
    },
    {
      label: "EF (RV)",
      value: `${fmt(features.ef_rv)} %`,
      sub: "Right ventricular ejection fraction",
      color: features.ef_rv < 40 ? "text-red-700" : features.ef_rv < 55 ? "text-amber-700" : "text-emerald-700",
      bg: features.ef_rv < 40 ? "bg-red-50" : features.ef_rv < 55 ? "bg-amber-50" : "bg-emerald-50",
    },
    {
      label: "ED vol (LV)",
      value: `${fmt(features.ed_vol_lv)} mL`,
      sub: "End-diastolic LV volume",
      color: "text-blue-700",
      bg: "bg-blue-50",
    },
    {
      label: "ES vol (LV)",
      value: `${fmt(features.es_vol_lv)} mL`,
      sub: "End-systolic LV volume",
      color: "text-violet-700",
      bg: "bg-violet-50",
    },
  ]

  return (
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
      {metrics.map((m) => (
        <div key={m.label} className={cn("rounded-lg p-2.5", m.bg)}>
          <p className={cn("text-[14px] font-bold tabular-nums", m.color)}>{m.value}</p>
          <p className="mt-0.5 text-[10px] font-medium text-[#102F27]/80">{m.label}</p>
          <p className="text-[9px] text-[#102F27]/50">{m.sub}</p>
        </div>
      ))}
    </div>
  )
}

function ClinicalFeaturesTable({ features }: { features: MriClinicalFeatures }) {
  const rows: { group: string; items: { label: string; ed: string; es: string }[] }[] = [
    {
      group: "Ventricular Volumes",
      items: [
        { label: "LV Volume",    ed: `${fmt(features.ed_vol_lv)} mL`, es: `${fmt(features.es_vol_lv)} mL` },
        { label: "RV Volume",    ed: `${fmt(features.ed_vol_rv)} mL`, es: `${fmt(features.es_vol_rv)} mL` },
      ],
    },
    {
      group: "Myocardial Mass / Volume",
      items: [
        { label: "Myo Mass/Vol",  ed: `${fmt(features.ed_mass_myo)} g`,  es: `${fmt(features.es_vol_myo)} mL` },
        { label: "Myo/LV ratio",  ed: fmt(features.ed_ratio_myo_lv, 2), es: fmt(features.es_ratio_myo_lv, 2) },
      ],
    },
    {
      group: "LV / RV Volume Ratio",
      items: [
        { label: "LV/RV ratio", ed: fmt(features.ed_ratio_lv_rv, 2), es: fmt(features.es_ratio_lv_rv, 2) },
      ],
    },
    {
      group: "Myocardial Wall Thickness (MWT)",
      items: [
        { label: "max(mean MWT)",   ed: fmt(features.ed_max_mean_mwt),    es: fmt(features.es_max_mean_mwt) },
        { label: "std(mean MWT)",   ed: fmt(features.ed_stdev_mean_mwt),  es: fmt(features.es_stdev_mean_mwt) },
        { label: "mean(std MWT)",   ed: fmt(features.ed_mean_stdev_mwt),  es: fmt(features.es_mean_stdev_mwt) },
        { label: "std(std MWT)",    ed: fmt(features.ed_stdev_stdev_mwt), es: fmt(features.es_stdev_stdev_mwt) },
      ],
    },
  ]

  return (
    <div className="overflow-hidden rounded-xl border border-[#E5EEEA]">
      <div className="flex items-center gap-2 border-b border-[#E5EEEA] bg-[#F6FBF9] px-4 py-2.5">
        <ActivityIcon className="size-3.5 text-[#1A5345]" />
        <span className="text-[12px] font-semibold text-[#102F27]">Clinical Feature Breakdown</span>
        <span className="ml-auto text-[11px] text-muted-foreground">20 manual features · ACDC pipeline</span>
      </div>

      <table className="w-full text-[12px]">
        <thead>
          <tr className="border-b border-[#E5EEEA] bg-[#FAFAF8]">
            <th className="py-2 pl-4 text-left font-semibold text-[#102F27]/60">Feature</th>
            <th className="py-2 text-center font-semibold text-blue-600">ED</th>
            <th className="py-2 pr-4 text-center font-semibold text-violet-600">ES</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((group) => (
            <>
              <tr key={group.group} className="border-t border-[#E5EEEA] bg-[#F9F8F5]">
                <td colSpan={3} className="py-1.5 pl-4 text-[11px] font-bold uppercase tracking-wider text-[#1A5345]/70">
                  {group.group}
                </td>
              </tr>
              {group.items.map((item) => (
                <tr
                  key={item.label}
                  className="border-t border-[#F0EDE8] transition-colors hover:bg-[#F6FBF9]"
                >
                  <td className="py-2.5 pl-4 text-[#102F27]/80">{item.label}</td>
                  <td className="py-2.5 text-center font-medium tabular-nums text-blue-700">{item.ed}</td>
                  <td className="py-2.5 pr-4 text-center font-medium tabular-nums text-violet-700">{item.es}</td>
                </tr>
              ))}
            </>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ─── dark viz panel (matches CTScanSection SliceGrid style) ──────────────────

function VizDarkPanel({
  title,
  icon: Icon,
  description,
  imgB64,
  mime = "image/png",
}: {
  title: string
  icon: LucideIcon
  description: string
  imgB64?: string
  mime?: "image/png" | "image/gif"
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-[#1d2b22] bg-[#0d1117]">
      <div className="flex items-center gap-2 border-b border-[#1d2b22] px-3 py-2">
        <div className="size-2 rounded-full bg-red-500/70" />
        <div className="size-2 rounded-full bg-amber-500/70" />
        <div className="size-2 rounded-full bg-emerald-500/70" />
        <Icon className="ml-1 size-3 text-[#8b949e]" />
        <span className="text-[10px] font-medium text-[#8b949e]">{title}</span>
      </div>
      <div className="h-72 overflow-y-auto">
        {imgB64 ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={`data:${mime};base64,${imgB64}`} alt={title} className="w-full" />
        ) : (
          <div className="flex h-full flex-col items-center justify-center gap-2 px-4">
            <Icon className="size-8 text-[#2a3e32]" />
            <p className="text-[11px] font-medium text-[#8b949e]">{title}</p>
            <p className="text-center text-[10px] text-[#4a5a51]">{description}</p>
            <span className="mt-1 rounded-full border border-[#2a3a30] px-2.5 py-0.5 text-[9px] text-[#5a7a6a]">
              Generated by ML service · pending connection
            </span>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── result panel ─────────────────────────────────────────────────────────────

function MriResultPanel({ result, elapsedSec }: { result: MriResult; elapsedSec: number }) {
  const cfg = DIAGNOSIS_CONFIG[result.diagnosisClass]

  return (
    <div className="space-y-3">
      <div className={cn("rounded-xl border-2 p-4 space-y-3", cfg.bg, cfg.border)}>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className={cn("flex size-7 shrink-0 items-center justify-center rounded-lg border", cfg.border, "bg-white")}>
              <BrainCircuitIcon className={cn("size-3.5", cfg.text)} />
            </div>
            <div>
              <p className={cn("text-[12px] font-semibold", cfg.text)}>Analysis Complete</p>
              <p className="text-[10px] text-[#102F27]/60">
                FCT Segmentation · VAE + Manual Features · Ensemble Classifier · {formatElapsed(elapsedSec)}
              </p>
            </div>
          </div>
          <CheckCircle2Icon className={cn("size-4", cfg.text)} />
        </div>

        <Separator className="bg-[#E5EEEA]" />

        <DiagnosisClassCard diagnosisClass={result.diagnosisClass} />
        <KeyMetricsGrid features={result.clinicalFeatures} />
      </div>

      {/* ── Animations ─────────────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <VizDarkPanel
          title="Raw Cine-MRI Loop"
          icon={FilmIcon}
          description="Animated loop of all MRI slices (ED + ES concatenated) in grayscale — no segmentation overlay."
          imgB64={result.rawGifB64}
          mime="image/gif"
        />
        <VizDarkPanel
          title="Segmentation Animation (ED ↔ ES)"
          icon={FilmIcon}
          description="Animated overlay alternating ED ↔ ES frames. Cyan = LV · Orange = Myocardium · Magenta = RV."
          imgB64={result.segGifB64}
          mime="image/gif"
        />
      </div>

      {/* ── Segmentation grids ─────────────────────────────────────────────── */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <VizDarkPanel
          title="Segmentation Grid — ED Phase"
          icon={LayoutGridIcon}
          description="Per-slice segmentation masks overlaid on grayscale frames for the End-Diastolic phase."
          imgB64={result.segGridEdB64}
        />
        <VizDarkPanel
          title="Segmentation Grid — ES Phase"
          icon={LayoutGridIcon}
          description="Per-slice segmentation masks overlaid on grayscale frames for the End-Systolic phase."
          imgB64={result.segGridEsB64}
        />
      </div>

      {/* ── Clinical features table ────────────────────────────────────────── */}
      <ClinicalFeaturesTable features={result.clinicalFeatures} />

      {/* ── Mean signal chart ─────────────────────────────────────────────── */}
      <div className="overflow-hidden rounded-xl border border-[#1d2b22] bg-[#0d1117]">
        <div className="flex items-center gap-2 border-b border-[#1d2b22] px-3 py-2">
          <div className="size-2 rounded-full bg-red-500/70" />
          <div className="size-2 rounded-full bg-amber-500/70" />
          <div className="size-2 rounded-full bg-emerald-500/70" />
          <TrendingUpIcon className="ml-1 size-3 text-[#8b949e]" />
          <span className="text-[10px] font-medium text-[#8b949e]">Mean Signal Intensity per Slice — ED vs ES</span>
        </div>
        <div className="h-72">
          {result.meanSignalChartJson ? (
            <MriPlotlyChart data={result.meanSignalChartJson} />
          ) : (
            <div className="flex h-full flex-col items-center justify-center gap-2 px-4">
              <TrendingUpIcon className="size-8 text-[#2a3e32]" />
              <p className="text-[11px] font-medium text-[#8b949e]">Mean Signal Intensity per Slice — ED vs ES</p>
              <p className="text-center text-[10px] text-[#4a5a51]">Line chart: mean voxel intensity across all slices comparing ED (blue) and ES (red) phases.</p>
              <span className="mt-1 rounded-full border border-[#2a3a30] px-2.5 py-0.5 text-[9px] text-[#5a7a6a]">
                Generated by ML service · pending connection
              </span>
            </div>
          )}
        </div>
      </div>

      {/* ── Overview 4-row grid ────────────────────────────────────────────── */}
      <VizDarkPanel
        title="Overview: ED vs ES"
        icon={LayersIcon}
        description="4-row × N-slice grid: (1) ED grayscale · (2) ES grayscale · (3) ED−ES pixel difference (RdBu) · (4) colour overlay R=ED G=ES."
        imgB64={result.overviewImgB64}
      />

      {/* ── Intensity histogram ────────────────────────────────────────────── */}
      <VizDarkPanel
        title="Intensity Histogram — ED vs ES"
        icon={BarChart2Icon}
        description="Side-by-side histogram of voxel intensity distributions: ED (blue) and ES (red)."
        imgB64={result.histogramImgB64}
      />

      {/* ── Thickening map + wall motion ───────────────────────────────────── */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div className="overflow-hidden rounded-xl border border-[#1d2b22] bg-[#0d1117]">
          <div className="flex items-center gap-2 border-b border-[#1d2b22] px-3 py-2">
            <div className="size-2 rounded-full bg-red-500/70" />
            <div className="size-2 rounded-full bg-amber-500/70" />
            <div className="size-2 rounded-full bg-emerald-500/70" />
            <BarChart2Icon className="ml-1 size-3 text-[#8b949e]" />
            <span className="text-[10px] font-medium text-[#8b949e]">Thickening Map — Myocardial Area per Slice</span>
          </div>
          <div className="h-72">
            {result.thickeningChartJson ? (
              <MriPlotlyChart data={result.thickeningChartJson} />
            ) : (
              <div className="flex h-full flex-col items-center justify-center gap-2 px-4">
                <BarChart2Icon className="size-8 text-[#2a3e32]" />
                <p className="text-[11px] font-medium text-[#8b949e]">Thickening Map — Myocardial Area per Slice</p>
                <p className="text-center text-[10px] text-[#4a5a51]">Grouped bar chart: myocardial pixel count per slice in ED vs ES.</p>
                <span className="mt-1 rounded-full border border-[#2a3a30] px-2.5 py-0.5 text-[9px] text-[#5a7a6a]">
                  Generated by ML service · pending connection
                </span>
              </div>
            )}
          </div>
        </div>
        <div className="overflow-hidden rounded-xl border border-[#1d2b22] bg-[#0d1117]">
          <div className="flex items-center gap-2 border-b border-[#1d2b22] px-3 py-2">
            <div className="size-2 rounded-full bg-red-500/70" />
            <div className="size-2 rounded-full bg-amber-500/70" />
            <div className="size-2 rounded-full bg-emerald-500/70" />
            <MoveIcon className="ml-1 size-3 text-[#8b949e]" />
            <span className="text-[10px] font-medium text-[#8b949e]">Wall Motion — LV Centroid Displacement</span>
          </div>
          <div className="h-72">
            {result.wallMotionChartJson ? (
              <MriPlotlyChart data={result.wallMotionChartJson} />
            ) : (
              <div className="flex h-full flex-col items-center justify-center gap-2 px-4">
                <MoveIcon className="size-8 text-[#2a3e32]" />
                <p className="text-[11px] font-medium text-[#8b949e]">Wall Motion — LV Centroid Displacement</p>
                <p className="text-center text-[10px] text-[#4a5a51]">LV centroid displacement from ED to ES per slice.</p>
                <span className="mt-1 rounded-full border border-[#2a3a30] px-2.5 py-0.5 text-[9px] text-[#5a7a6a]">
                  Generated by ML service · pending connection
                </span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── 3D rendering ───────────────────────────────────────────────────── */}
      <div className="overflow-hidden rounded-xl border border-[#1d2b22] bg-[#0d1117]">
        <div className="flex items-center gap-2 border-b border-[#1d2b22] px-3 py-2">
          <div className="size-2 rounded-full bg-red-500/70" />
          <div className="size-2 rounded-full bg-amber-500/70" />
          <div className="size-2 rounded-full bg-emerald-500/70" />
          <BoxIcon className="ml-1 size-3 text-[#8b949e]" />
          <span className="text-[10px] font-medium text-[#8b949e]">3D Cardiac Structure Rendering — ED Phase</span>
        </div>
        <div className="h-96">
          {result.rendering3dJson ? (
            <MriPlotlyChart data={result.rendering3dJson} className="h-96 w-full" />
          ) : (
            <div className="flex h-full flex-col items-center justify-center gap-2 px-4">
              <BoxIcon className="size-8 text-[#2a3e32]" />
              <p className="text-[11px] font-medium text-[#8b949e]">3D Cardiac Structure Rendering — ED Phase</p>
              <p className="text-center text-[10px] text-[#4a5a51]">3D point cloud: LV, Myocardium, RV from ED segmentation masks.</p>
              <span className="mt-1 rounded-full border border-[#2a3a30] px-2.5 py-0.5 text-[9px] text-[#5a7a6a]">
                Generated by ML service · pending connection
              </span>
            </div>
          )}
        </div>
      </div>

      {/* ── MPR ────────────────────────────────────────────────────────────── */}
      <VizDarkPanel
        title="Multi-Planar Reformatting (MPR)"
        icon={SplitIcon}
        description="Axial · Sagittal · Coronal views for ED (top row) and ES (bottom row) phases."
        imgB64={result.mprImgB64}
      />

      {/* ── Footer ─────────────────────────────────────────────────────────── */}
      <div className="rounded-lg border border-[#E5EEEA] bg-[#FAFAF8] px-4 py-3">
        <p className="text-[10px] text-muted-foreground">
          <span className="font-semibold text-[#102F27]">Model:</span> FCT segmentation → VAE (32 deep features) + 20 manual clinical
          features → Voting Classifier (MLP + Random Forest + SVM). Trained on the ACDC dataset — 5 classes, ~92%
          accuracy. Results are for clinical decision support only and do not replace physician judgement.
        </p>
      </div>
    </div>
  )
}

function MriErrorPanel({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <div className="rounded-lg border border-red-200 bg-red-50 p-3">
      <div className="flex items-start gap-2">
        <XCircleIcon className="mt-0.5 size-4 shrink-0 text-red-500" />
        <div className="min-w-0 flex-1">
          <p className="text-[11px] font-semibold text-red-700">Analysis failed</p>
          <p className="mt-0.5 text-[10px] text-red-600">{message}</p>
          <p className="mt-1 text-[10px] text-red-500/80">
            Make sure both ED and ES NIfTI files are valid cardiac MRI scans.
          </p>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={onRetry}
          className="shrink-0 border-red-200 text-[11px] text-red-600 hover:bg-red-100 hover:text-red-700"
        >
          Retry
        </Button>
      </div>
    </div>
  )
}

// ─── main section ─────────────────────────────────────────────────────────────

export type CineMRISectionProps = {
  edFile: File | null
  onEdFileChange: (file: File | null) => void
  esFile: File | null
  onEsFileChange: (file: File | null) => void
}

export function CineMRISection({ edFile, onEdFileChange, esFile, onEsFileChange }: CineMRISectionProps) {
  const [status, setStatus] = useState<AnalysisStatus>("idle")
  const [result, setResult] = useState<MriResult | null>(null)
  const [errorMsg, setErrorMsg] = useState("")
  const [elapsed, setElapsed] = useState(0)
  const [aiChatOpen, setAiChatOpen] = useState(false)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const reset = () => {
    setStatus("idle")
    setResult(null)
    setErrorMsg("")
    setElapsed(0)
    if (timerRef.current) clearInterval(timerRef.current)
  }

  const handleEdFileSelected = (file: File) => {
    reset()
    onEdFileChange(file)
  }

  const handleEsFileSelected = (file: File) => {
    reset()
    onEsFileChange(file)
  }

  const handleRemoveEd = () => {
    reset()
    onEdFileChange(null)
  }

  const handleRemoveEs = () => {
    reset()
    onEsFileChange(null)
  }

  const handleAnalyze = async () => {
    if (!edFile || !esFile) return
    reset()
    setStatus("processing")
    setElapsed(0)
    timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000)

    try {
      const formData = new FormData()
      formData.append("ed_file", edFile)
      formData.append("es_file", esFile)

      const res = await fetch(`${MRI_URL}/predict`, {
        method: "POST",
        body: formData,
      })

      if (!res.ok) {
        const text = await res.text().catch(() => `HTTP ${res.status}`)
        throw new Error(text || `HTTP ${res.status}`)
      }

      const json = await res.json()

      setResult({
        diagnosisClass:       json.diagnosis_class,
        elapsedSec:           json.elapsed_sec,
        clinicalFeatures:     json.clinical_features,
        rawGifB64:            json.raw_gif_b64,
        segGifB64:            json.seg_gif_b64,
        segGridEdB64:         json.seg_grid_ed_b64,
        segGridEsB64:         json.seg_grid_es_b64,
        meanSignalChartJson:  json.mean_signal_chart_json,
        overviewImgB64:       json.overview_img_b64,
        histogramImgB64:      json.histogram_img_b64,
        thickeningChartJson:  json.thickening_chart_json,
        wallMotionChartJson:  json.wall_motion_chart_json,
        rendering3dJson:      json.rendering_3d_json,
        mprImgB64:            json.mpr_img_b64,
      })
      setStatus("done")
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Unknown error")
      setStatus("error")
    } finally {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }

  const bothFilesReady = edFile !== null && esFile !== null
  const showAnalyzeButton = bothFilesReady && status !== "done" && status !== "error"

  return (
    <div className="rounded-xl border-2 border-[#E5EEEA] bg-white p-5">
      {/* Header */}
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex size-7 items-center justify-center rounded-lg bg-[#E8F0EE]">
            <ScanHeartIcon className="size-4 text-[#1A5345]" />
          </div>
          <h3 className="text-[14px] font-semibold text-[#102F27]">Cardiac Cine-MRI Analysis</h3>
        </div>
        <span className="rounded-full bg-violet-50 px-2.5 py-0.5 text-[10px] font-medium text-violet-600">
          AI · FCT + Ensemble
        </span>
      </div>

      <div className="space-y-3">
        {/* Upload pair */}
        <div className="grid grid-cols-2 gap-3">
          {edFile ? (
            <MriFileCard
              file={edFile}
              phase="ED"
              status={status}
              elapsed={elapsed}
              onRemove={handleRemoveEd}
            />
          ) : (
            <MriDropZone phase="ED" onFileSelected={handleEdFileSelected} />
          )}

          {esFile ? (
            <MriFileCard
              file={esFile}
              phase="ES"
              status={status}
              elapsed={elapsed}
              onRemove={handleRemoveEs}
            />
          ) : (
            <MriDropZone phase="ES" onFileSelected={handleEsFileSelected} />
          )}
        </div>

        {!bothFilesReady && (
          <p className="text-center text-[10px] text-muted-foreground">
            Upload both the <span className="font-semibold text-blue-600">End-Diastolic (ED)</span> and{" "}
            <span className="font-semibold text-violet-600">End-Systolic (ES)</span> NIfTI scans to run the analysis.
          </p>
        )}

        {status === "done" && result && (
          <>
            <MriResultPanel result={result} elapsedSec={result.elapsedSec || elapsed} />
            <Button
              size="sm"
              onClick={() => setAiChatOpen(true)}
              className="w-full gap-1.5 bg-violet-600 text-[12px] hover:bg-violet-700"
            >
              <SparklesIcon className="size-3.5" />
              AI Summary &amp; Recommendations
            </Button>
            <CineMRIAiChatDialog
              open={aiChatOpen}
              onOpenChange={setAiChatOpen}
              result={result}
            />
          </>
        )}

        {status === "error" && (
          <MriErrorPanel message={errorMsg} onRetry={handleAnalyze} />
        )}

        {showAnalyzeButton && (
          <Button
            size="sm"
            disabled={status === "processing"}
            onClick={handleAnalyze}
            className="w-full gap-1.5 bg-[#1A5345] text-[12px] hover:bg-[#0F3D32]"
          >
            {status === "processing" ? (
              <>
                <Loader2Icon className="size-3.5 animate-spin" />
                Running MRI pipeline…
              </>
            ) : (
              <>
                <BrainCircuitIcon className="size-3.5" />
                Run Cardiac MRI Analysis
              </>
            )}
          </Button>
        )}

        <p className="text-center text-[10px] text-muted-foreground">
          Upload cardiac Cine-MRI scans in NIfTI format (.nii / .nii.gz). Requires separate ED and ES phase files.
          Pipeline: FCT segmentation → VAE deep features + 20 manual clinical features → Ensemble classification.
        </p>
      </div>
    </div>
  )
}
