"use client"

import { useCallback, useRef, useState } from "react"
import { cn } from "@/lib/utils"
import type { LucideIcon } from "lucide-react"
import {
  ActivityIcon,
  BarChart2Icon,
  BoxIcon,
  BrainCircuitIcon,
  CheckCircle2Icon,
  ClockIcon,
  FileIcon,
  FilmIcon,
  HeartPulseIcon,
  LayersIcon,
  LayoutGridIcon,
  Loader2Icon,
  MoveIcon,
  ScanHeartIcon,
  SparklesIcon,
  SplitIcon,
  Trash2Icon,
  TrendingUpIcon,
  UploadCloudIcon,
  XCircleIcon,
} from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { CineMRIAiChatDialog } from "./CineMRIAiChatDialog"
import { MriPlotlyChart } from "./MriPlotlyChart"

// ─── types ────────────────────────────────────────────────────────────────────

type AnalysisStatus = "idle" | "processing" | "done" | "error"

export type MriDiagnosisClass = "NOR" | "HCM" | "DCM" | "MINF" | "RV"

export interface MriClinicalFeatures {
  ed_vol_lv: number
  es_vol_lv: number
  ed_vol_rv: number
  es_vol_rv: number
  ed_mass_myo: number
  es_vol_myo: number
  ef_lv: number
  ef_rv: number
  ed_ratio_lv_rv: number
  es_ratio_lv_rv: number
  ed_ratio_myo_lv: number
  es_ratio_myo_lv: number
  es_max_mean_mwt: number
  es_stdev_mean_mwt: number
  es_mean_stdev_mwt: number
  es_stdev_stdev_mwt: number
  ed_max_mean_mwt: number
  ed_stdev_mean_mwt: number
  ed_mean_stdev_mwt: number
  ed_stdev_stdev_mwt: number
}

export interface MriResult {
  diagnosisClass: MriDiagnosisClass
  clinicalFeatures: MriClinicalFeatures
  elapsedSec: number
  // Visualizations — base64 images generated by the ML service
  rawGifB64?: string           // display_video()         — raw cine loop (grayscale)
  segGifB64?: string           // build_seg_gif()         — segmentation overlay animation (ED ↔ ES)
  segGridEdB64?: string        // display_seg_grid(ED)    — per-slice ED mask grid
  segGridEsB64?: string        // display_seg_grid(ES)    — per-slice ES mask grid
  meanSignalChartJson?: unknown // plot_mean_signal()      — interactive line chart (Plotly)
  overviewImgB64?: string      // display_overview()      — 4-row comparison grid
  histogramImgB64?: string     // plot_intensity_histogram() — ED vs ES voxel histograms
  thickeningChartJson?: unknown // plot_thickening_map()  — interactive bar chart (Plotly)
  wallMotionChartJson?: unknown // plot_wall_motion()    — interactive line chart (Plotly)
  rendering3dJson?: unknown    // display_3d_rendering()  — interactive 3D scatter (Plotly)
  mprImgB64?: string           // display_mpr()           — Axial / Sagittal / Coronal views
}

// ─── service URL ─────────────────────────────────────────────────────────────

const MRI_URL =
  typeof window !== "undefined"
    ? (process.env.NEXT_PUBLIC_MRI_SERVICE_URL ?? "http://localhost:8090")
    : "http://localhost:8090"

// ─── constants ────────────────────────────────────────────────────────────────

const SECTION_CARD = "rounded-2xl border border-[#E8E6E0]/60 bg-white p-5 shadow-sm"
const STAT_CARD =
  "rounded-xl border border-[#E8E6E0]/60 bg-white p-3 shadow-sm transition-shadow hover:shadow-md"

const DIAGNOSIS_CONFIG: Record<
  MriDiagnosisClass,
  { label: string; description: string; badge: string; text: string; bg: string; border: string }
> = {
  NOR: {
    label: "Normal",
    description: "No significant structural or functional cardiac abnormality detected.",
    badge: "bg-emerald-500 text-white hover:bg-emerald-500",
    text: "text-emerald-800",
    bg: "bg-emerald-50/60",
    border: "border-emerald-200",
  },
  HCM: {
    label: "Hypertrophic Cardiomyopathy",
    description: "Abnormal thickening of the myocardial wall, typically affecting the interventricular septum.",
    badge: "bg-amber-500 text-white hover:bg-amber-500",
    text: "text-amber-800",
    bg: "bg-amber-50/60",
    border: "border-amber-200",
  },
  DCM: {
    label: "Dilated Cardiomyopathy",
    description: "Enlarged, weakened left ventricle with significantly reduced ejection fraction.",
    badge: "bg-orange-500 text-white hover:bg-orange-500",
    text: "text-orange-800",
    bg: "bg-orange-50/60",
    border: "border-orange-200",
  },
  MINF: {
    label: "Myocardial Infarction",
    description: "Evidence of regional wall motion abnormality consistent with prior myocardial infarction.",
    badge: "bg-red-500 text-white hover:bg-red-500",
    text: "text-red-800",
    bg: "bg-red-50/60",
    border: "border-red-200",
  },
  RV: {
    label: "Right Ventricular Disease",
    description: "Abnormal right ventricular size or function relative to the left ventricle.",
    badge: "bg-violet-500 text-white hover:bg-violet-500",
    text: "text-violet-800",
    bg: "bg-violet-50/60",
    border: "border-violet-200",
  },
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatElapsed(sec: number): string {
  if (sec < 60) return `${sec}s`
  return `${Math.floor(sec / 60)}m ${sec % 60}s`
}

function fmt(n: number, decimals = 1): string {
  return n.toFixed(decimals)
}

// ─── sub-components ───────────────────────────────────────────────────────────

function MriDropZone({
  phase,
  onFileSelected,
}: {
  phase: "ED" | "ES"
  onFileSelected: (file: File) => void
}) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [isDragging, setIsDragging] = useState(false)

  const handleFiles = useCallback(
    (files: FileList | null) => {
      if (!files?.length) return
      const file = files[0]
      if (!file.name.endsWith(".nii") && !file.name.endsWith(".nii.gz")) return
      onFileSelected(file)
    },
    [onFileSelected],
  )

  const phaseLabel = phase === "ED" ? "End-diastolic (ED)" : "End-systolic (ES)"
  const phaseBadge =
    phase === "ED"
      ? "bg-blue-500 text-white hover:bg-blue-500"
      : "bg-violet-500 text-white hover:bg-violet-500"

  return (
    <div
      role="button"
      tabIndex={0}
      aria-label={`Upload ${phaseLabel} NIfTI scan`}
      onClick={() => inputRef.current?.click()}
      onKeyDown={(e) => e.key === "Enter" && inputRef.current?.click()}
      onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
      onDragLeave={() => setIsDragging(false)}
      onDrop={(e) => {
        e.preventDefault()
        setIsDragging(false)
        handleFiles(e.dataTransfer.files)
      }}
      className={cn(
        "flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed py-8 transition-colors",
        isDragging
          ? "border-[#1A5345]/50 bg-[#F0F7F4]"
          : "border-[#E8E6E0] bg-[#FAFAF8] hover:border-[#1A5345]/30 hover:bg-[#F9F8F5]",
      )}
    >
      <Badge
        variant="default"
        className={cn("rounded-lg border-0 px-2.5 py-0.5 text-[10px] font-bold shadow-none", phaseBadge)}
      >
        {phase}
      </Badge>
      <UploadCloudIcon
        className={cn("size-8", isDragging ? "text-[#1A5345]" : "text-[#1A5345]/80")}
        aria-hidden
      />
      <div className="text-center">
        <p className="text-[14px] font-medium text-[#1A1F1E]">{phaseLabel}</p>
        <p className="mt-1 text-[12px] text-muted-foreground">
          Drop or{" "}
          <span className="font-semibold text-[#1A5345] underline underline-offset-2">browse</span>
          {" "}· .nii / .nii.gz
        </p>
      </div>
      <input
        ref={inputRef}
        type="file"
        accept=".nii,.nii.gz"
        className="sr-only"
        onChange={(e) => handleFiles(e.target.files)}
      />
    </div>
  )
}

function MriFileCard({
  file,
  phase,
  status,
  elapsed,
  onRemove,
}: {
  file: File
  phase: "ED" | "ES"
  status: AnalysisStatus
  elapsed: number
  onRemove: () => void
}) {
  const phaseBadge =
    phase === "ED"
      ? "bg-blue-500 text-white hover:bg-blue-500"
      : "bg-violet-500 text-white hover:bg-violet-500"

  const statusMap = {
    idle:       { badge: "",                                icon: null,             label: "" },
    processing: { badge: "bg-amber-500 text-white hover:bg-amber-500", icon: Loader2Icon, label: "Analyzing" },
    done:       { badge: "bg-emerald-500 text-white hover:bg-emerald-500", icon: CheckCircle2Icon, label: "Done" },
    error:      { badge: "bg-rose-500 text-white hover:bg-rose-500", icon: XCircleIcon, label: "Failed" },
  }
  const cfg = statusMap[status]
  const Icon = cfg.icon

  return (
    <div className="overflow-hidden rounded-xl border border-[#E8E6E0]/60 bg-white shadow-sm">
      <div className="flex items-center gap-3 border-b border-[#E8E6E0]/60 bg-[#F9F8F5] px-4 py-3">
        <FileIcon className="size-5 shrink-0 text-[#1A5345]" aria-hidden />
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <Badge
              variant="default"
              className={cn("rounded-lg border-0 px-2 py-0.5 text-[10px] font-bold shadow-none", phaseBadge)}
            >
              {phase}
            </Badge>
            <p className="truncate text-[14px] font-semibold text-[#1A1F1E]">{file.name}</p>
          </div>
          <div className="mt-0.5 flex flex-wrap items-center gap-2">
            <span className="text-[12px] text-muted-foreground">{formatBytes(file.size)}</span>
            {status === "processing" && elapsed > 0 && (
              <span className="flex items-center gap-1 text-[12px] text-muted-foreground">
                <ClockIcon className="size-3" aria-hidden />
                {formatElapsed(elapsed)}
              </span>
            )}
          </div>
        </div>
        {Icon && (
          <Badge
            variant="default"
            className={cn("gap-1 rounded-lg border-0 px-2.5 py-1 text-[11px] font-bold shadow-none", cfg.badge)}
          >
            <Icon className={cn("size-3", status === "processing" && "animate-spin")} aria-hidden />
            {cfg.label}
          </Badge>
        )}
        <Button
          type="button"
          size="icon"
          variant="ghost"
          disabled={status === "processing"}
          className="size-8 shrink-0 border-0 bg-transparent text-muted-foreground shadow-none hover:bg-transparent hover:text-rose-600"
          onClick={onRemove}
          aria-label="Remove file"
        >
          <Trash2Icon className="size-4" />
        </Button>
      </div>
    </div>
  )
}

function DiagnosisClassCard({ diagnosisClass }: { diagnosisClass: MriDiagnosisClass }) {
  const cfg = DIAGNOSIS_CONFIG[diagnosisClass]

  return (
    <div className={cn("rounded-xl border p-4", cfg.bg, cfg.border)}>
      <div className="flex items-start gap-3">
        <HeartPulseIcon className={cn("mt-0.5 size-5 shrink-0", cfg.text)} aria-hidden />
        <div className="flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <Badge
              variant="default"
              className={cn("rounded-lg border-0 px-2.5 py-0.5 text-[11px] font-bold shadow-none", cfg.badge)}
            >
              {diagnosisClass}
            </Badge>
            <p className={cn("text-[14px] font-bold", cfg.text)}>{cfg.label}</p>
          </div>
          <p className="mt-1.5 text-[13px] leading-relaxed text-[#374151]">{cfg.description}</p>
        </div>
        <CheckCircle2Icon className={cn("size-5 shrink-0", cfg.text)} aria-hidden />
      </div>
    </div>
  )
}

function KeyMetricsGrid({ features }: { features: MriClinicalFeatures }) {
  const metrics = [
    {
      label: "EF (LV)",
      value: `${fmt(features.ef_lv)} %`,
      sub: "Left ventricular ejection fraction",
      color: features.ef_lv < 40 ? "text-red-700" : features.ef_lv < 55 ? "text-amber-700" : "text-emerald-700",
      bg: features.ef_lv < 40 ? "bg-red-50" : features.ef_lv < 55 ? "bg-amber-50" : "bg-emerald-50",
    },
    {
      label: "EF (RV)",
      value: `${fmt(features.ef_rv)} %`,
      sub: "Right ventricular ejection fraction",
      color: features.ef_rv < 40 ? "text-red-700" : features.ef_rv < 55 ? "text-amber-700" : "text-emerald-700",
      bg: features.ef_rv < 40 ? "bg-red-50" : features.ef_rv < 55 ? "bg-amber-50" : "bg-emerald-50",
    },
    {
      label: "ED vol (LV)",
      value: `${fmt(features.ed_vol_lv)} mL`,
      sub: "End-diastolic LV volume",
      color: "text-blue-700",
      bg: "bg-blue-50",
    },
    {
      label: "ES vol (LV)",
      value: `${fmt(features.es_vol_lv)} mL`,
      sub: "End-systolic LV volume",
      color: "text-violet-700",
      bg: "bg-violet-50",
    },
  ]

  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
      {metrics.map((m) => (
        <div key={m.label} className={cn("space-y-1", STAT_CARD)}>
          <p className={cn("text-[16px] font-bold tabular-nums", m.color)}>{m.value}</p>
          <p className="text-[12px] font-semibold text-[#1A1F1E]">{m.label}</p>
          <p className="text-[11px] text-muted-foreground">{m.sub}</p>
        </div>
      ))}
    </div>
  )
}

function ClinicalFeaturesTable({ features }: { features: MriClinicalFeatures }) {
  const rows: { group: string; items: { label: string; ed: string; es: string }[] }[] = [
    {
      group: "Ventricular Volumes",
      items: [
        { label: "LV Volume",    ed: `${fmt(features.ed_vol_lv)} mL`, es: `${fmt(features.es_vol_lv)} mL` },
        { label: "RV Volume",    ed: `${fmt(features.ed_vol_rv)} mL`, es: `${fmt(features.es_vol_rv)} mL` },
      ],
    },
    {
      group: "Myocardial Mass / Volume",
      items: [
        { label: "Myo Mass/Vol",  ed: `${fmt(features.ed_mass_myo)} g`,  es: `${fmt(features.es_vol_myo)} mL` },
        { label: "Myo/LV ratio",  ed: fmt(features.ed_ratio_myo_lv, 2), es: fmt(features.es_ratio_myo_lv, 2) },
      ],
    },
    {
      group: "LV / RV Volume Ratio",
      items: [
        { label: "LV/RV ratio", ed: fmt(features.ed_ratio_lv_rv, 2), es: fmt(features.es_ratio_lv_rv, 2) },
      ],
    },
    {
      group: "Myocardial Wall Thickness (MWT)",
      items: [
        { label: "max(mean MWT)",   ed: fmt(features.ed_max_mean_mwt),    es: fmt(features.es_max_mean_mwt) },
        { label: "std(mean MWT)",   ed: fmt(features.ed_stdev_mean_mwt),  es: fmt(features.es_stdev_mean_mwt) },
        { label: "mean(std MWT)",   ed: fmt(features.ed_mean_stdev_mwt),  es: fmt(features.es_mean_stdev_mwt) },
        { label: "std(std MWT)",    ed: fmt(features.ed_stdev_stdev_mwt), es: fmt(features.es_stdev_stdev_mwt) },
      ],
    },
  ]

  return (
    <div className="overflow-hidden rounded-xl border border-[#E8E6E0]/60 bg-white shadow-sm">
      <div className="flex flex-wrap items-center gap-2 border-b border-[#E8E6E0]/60 bg-[#F9F8F5] px-4 py-3">
        <ActivityIcon className="size-4 text-[#1A5345]" aria-hidden />
        <span className="font-serif text-[14px] font-bold text-[#1A1F1E]">Clinical feature breakdown</span>
        <span className="ml-auto text-[12px] text-muted-foreground">20 manual features · ACDC pipeline</span>
      </div>

      <table className="w-full text-[13px]">
        <thead>
          <tr className="border-b border-[#E8E6E0]/60 bg-[#FAFAF8]">
            <th className="py-2.5 pl-4 text-left font-semibold text-muted-foreground">Feature</th>
            <th className="py-2.5 text-center font-semibold text-blue-600">ED</th>
            <th className="py-2.5 pr-4 text-center font-semibold text-violet-600">ES</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((group) => (
            <>
              <tr key={group.group} className="border-t border-[#E8E6E0]/60 bg-[#F9F8F5]">
                <td colSpan={3} className="py-2 pl-4 text-[11px] font-bold uppercase tracking-wider text-[#1A5345]">
                  {group.group}
                </td>
              </tr>
              {group.items.map((item) => (
                <tr
                  key={item.label}
                  className="border-t border-[#E8E6E0]/40 transition-colors hover:bg-[#F9F8F5]"
                >
                  <td className="py-2.5 pl-4 text-[#374151]">{item.label}</td>
                  <td className="py-2.5 text-center font-semibold tabular-nums text-blue-700">{item.ed}</td>
                  <td className="py-2.5 pr-4 text-center font-semibold tabular-nums text-violet-700">{item.es}</td>
                </tr>
              ))}
            </>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ─── visualization panels (assistant card chrome, dark image canvas) ───────────

function VizPanel({
  title,
  icon: Icon,
  description,
  imgB64,
  mime = "image/png",
  children,
  contentClassName,
}: {
  title: string
  icon: LucideIcon
  description: string
  imgB64?: string
  mime?: "image/png" | "image/gif"
  children?: React.ReactNode
  contentClassName?: string
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-[#E8E6E0]/60 bg-white shadow-sm">
      <div className="border-b border-[#E8E6E0]/60 bg-[#F9F8F5] px-4 py-3">
        <div className="flex items-center gap-2">
          <Icon className="size-4 shrink-0 text-[#1A5345]" aria-hidden />
          <h4 className="font-serif text-[14px] font-bold text-[#1A1F1E]">{title}</h4>
        </div>
        <p className="mt-0.5 text-[12px] text-muted-foreground">{description}</p>
      </div>
      <div className={cn("overflow-y-auto bg-[#102F27]", contentClassName ?? "max-h-80")}>
        {children ?? (
          imgB64 ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={`data:${mime};base64,${imgB64}`} alt={title} className="w-full object-contain" />
          ) : (
            <div className="flex h-48 flex-col items-center justify-center gap-2 px-4">
              <Icon className="size-8 text-[#8b949e]" aria-hidden />
              <p className="text-[12px] font-medium text-[#8b949e]">Awaiting ML service output</p>
            </div>
          )
        )}
      </div>
    </div>
  )
}

function VizChartPanel({
  title,
  icon: Icon,
  description,
  chartJson,
  contentClassName,
}: {
  title: string
  icon: LucideIcon
  description: string
  chartJson?: unknown
  contentClassName?: string
}) {
  return (
    <VizPanel
      title={title}
      icon={Icon}
      description={description}
      contentClassName={contentClassName ?? "h-72"}
    >
      {chartJson ? (
        <MriPlotlyChart data={chartJson} className={cn("w-full", contentClassName ?? "h-72")} />
      ) : undefined}
    </VizPanel>
  )
}

// ─── result panel ─────────────────────────────────────────────────────────────

function MriResultPanel({ result, elapsedSec }: { result: MriResult; elapsedSec: number }) {
  const cfg = DIAGNOSIS_CONFIG[result.diagnosisClass]

  return (
    <div className="space-y-4">
      <div className={cn("space-y-4 rounded-xl border p-4", cfg.bg, cfg.border)}>
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <BrainCircuitIcon className={cn("size-5 shrink-0", cfg.text)} aria-hidden />
            <div>
              <p className={cn("font-serif text-[15px] font-bold", cfg.text)}>Analysis complete</p>
              <p className="text-[12px] text-muted-foreground">
                FCT segmentation · VAE + manual features · ensemble · {formatElapsed(elapsedSec)}
              </p>
            </div>
          </div>
          <Badge
            variant="default"
            className="rounded-lg border-0 bg-emerald-500 px-2.5 py-1 text-[11px] font-bold text-white shadow-none hover:bg-emerald-500"
          >
            Ready for review
          </Badge>
        </div>

        <DiagnosisClassCard diagnosisClass={result.diagnosisClass} />
        <KeyMetricsGrid features={result.clinicalFeatures} />
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <VizPanel
          title="Raw cine-MRI loop"
          icon={FilmIcon}
          description="Animated loop of all MRI slices (ED + ES) in grayscale — no segmentation overlay."
          imgB64={result.rawGifB64}
          mime="image/gif"
        />
        <VizPanel
          title="Segmentation animation (ED ↔ ES)"
          icon={FilmIcon}
          description="Overlay alternating ED ↔ ES frames. Cyan = LV · Orange = myocardium · Magenta = RV."
          imgB64={result.segGifB64}
          mime="image/gif"
        />
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <VizPanel
          title="Segmentation grid — ED phase"
          icon={LayoutGridIcon}
          description="Per-slice segmentation masks on grayscale frames for end-diastolic phase."
          imgB64={result.segGridEdB64}
        />
        <VizPanel
          title="Segmentation grid — ES phase"
          icon={LayoutGridIcon}
          description="Per-slice segmentation masks on grayscale frames for end-systolic phase."
          imgB64={result.segGridEsB64}
        />
      </div>

      <ClinicalFeaturesTable features={result.clinicalFeatures} />

      <VizChartPanel
        title="Mean signal intensity per slice — ED vs ES"
        icon={TrendingUpIcon}
        description="Mean voxel intensity across slices comparing ED (blue) and ES (red) phases."
        chartJson={result.meanSignalChartJson}
      />

      <VizPanel
        title="Overview: ED vs ES"
        icon={LayersIcon}
        description="4-row grid: ED grayscale · ES grayscale · ED−ES difference · colour overlay R=ED G=ES."
        imgB64={result.overviewImgB64}
      />

      <VizPanel
        title="Intensity histogram — ED vs ES"
        icon={BarChart2Icon}
        description="Side-by-side voxel intensity distributions: ED (blue) and ES (red)."
        imgB64={result.histogramImgB64}
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <VizChartPanel
          title="Thickening map — myocardial area per slice"
          icon={BarChart2Icon}
          description="Grouped bar chart: myocardial pixel count per slice in ED vs ES."
          chartJson={result.thickeningChartJson}
        />
        <VizChartPanel
          title="Wall motion — LV centroid displacement"
          icon={MoveIcon}
          description="LV centroid displacement from ED to ES per slice."
          chartJson={result.wallMotionChartJson}
        />
      </div>

      <VizChartPanel
        title="3D cardiac structure — ED phase"
        icon={BoxIcon}
        description="3D point cloud: LV, myocardium, and RV from ED segmentation masks."
        chartJson={result.rendering3dJson}
        contentClassName="h-96"
      />

      <VizPanel
        title="Multi-planar reformatting (MPR)"
        icon={SplitIcon}
        description="Axial · sagittal · coronal views for ED (top) and ES (bottom) phases."
        imgB64={result.mprImgB64}
      />

      <div className="rounded-xl border border-[#E8E6E0]/60 bg-[#F9F8F5] px-4 py-3">
        <p className="text-[12px] leading-relaxed text-muted-foreground">
          <span className="font-semibold text-[#1A1F1E]">Model:</span> FCT segmentation → VAE (32 deep features) + 20 manual clinical
          features → voting classifier (MLP + random forest + SVM). Trained on ACDC — 5 classes, ~92% accuracy.
          Results are for clinical decision support only and do not replace physician judgement.
        </p>
      </div>
    </div>
  )
}

function MriErrorPanel({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <div className="rounded-xl border border-rose-200 bg-rose-50/80 p-4">
      <div className="flex items-start gap-3">
        <XCircleIcon className="mt-0.5 size-4 shrink-0 text-rose-600" aria-hidden />
        <div className="min-w-0 flex-1">
          <p className="text-[13px] font-semibold text-rose-800">Analysis failed</p>
          <p className="mt-1 text-[12px] text-rose-700">{message}</p>
          <p className="mt-2 text-[12px] text-rose-600/90">
            Make sure both ED and ES NIfTI files are valid cardiac MRI scans.
          </p>
        </div>
        <Button
          type="button"
          size="sm"
          variant="outline"
          onClick={onRetry}
          className="shrink-0 rounded-lg border-rose-200 bg-white text-[12px] text-rose-700 hover:bg-rose-50"
        >
          Retry
        </Button>
      </div>
    </div>
  )
}

// ─── main section ─────────────────────────────────────────────────────────────

export type CineMRISectionProps = {
  edFile: File | null
  onEdFileChange: (file: File | null) => void
  esFile: File | null
  onEsFileChange: (file: File | null) => void
}

export function CineMRISection({ edFile, onEdFileChange, esFile, onEsFileChange }: CineMRISectionProps) {
  const [status, setStatus] = useState<AnalysisStatus>("idle")
  const [result, setResult] = useState<MriResult | null>(null)
  const [errorMsg, setErrorMsg] = useState("")
  const [elapsed, setElapsed] = useState(0)
  const [aiChatOpen, setAiChatOpen] = useState(false)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const reset = () => {
    setStatus("idle")
    setResult(null)
    setErrorMsg("")
    setElapsed(0)
    if (timerRef.current) clearInterval(timerRef.current)
  }

  const handleEdFileSelected = (file: File) => {
    reset()
    onEdFileChange(file)
  }

  const handleEsFileSelected = (file: File) => {
    reset()
    onEsFileChange(file)
  }

  const handleRemoveEd = () => {
    reset()
    onEdFileChange(null)
  }

  const handleRemoveEs = () => {
    reset()
    onEsFileChange(null)
  }

  const handleAnalyze = async () => {
    if (!edFile || !esFile) return
    reset()
    setStatus("processing")
    setElapsed(0)
    timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000)

    try {
      const formData = new FormData()
      formData.append("ed_file", edFile)
      formData.append("es_file", esFile)

      const res = await fetch(`${MRI_URL}/predict`, {
        method: "POST",
        body: formData,
      })

      if (!res.ok) {
        const text = await res.text().catch(() => `HTTP ${res.status}`)
        throw new Error(text || `HTTP ${res.status}`)
      }

      const json = await res.json()

      setResult({
        diagnosisClass:       json.diagnosis_class,
        elapsedSec:           json.elapsed_sec,
        clinicalFeatures:     json.clinical_features,
        rawGifB64:            json.raw_gif_b64,
        segGifB64:            json.seg_gif_b64,
        segGridEdB64:         json.seg_grid_ed_b64,
        segGridEsB64:         json.seg_grid_es_b64,
        meanSignalChartJson:  json.mean_signal_chart_json,
        overviewImgB64:       json.overview_img_b64,
        histogramImgB64:      json.histogram_img_b64,
        thickeningChartJson:  json.thickening_chart_json,
        wallMotionChartJson:  json.wall_motion_chart_json,
        rendering3dJson:      json.rendering_3d_json,
        mprImgB64:            json.mpr_img_b64,
      })
      setStatus("done")
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Unknown error")
      setStatus("error")
    } finally {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }

  const bothFilesReady = edFile !== null && esFile !== null
  const showAnalyzeButton = bothFilesReady && status !== "done" && status !== "error"

  return (
    <div className={SECTION_CARD}>
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <ScanHeartIcon className="size-5 shrink-0 text-[#1A5345]" aria-hidden />
            <h3 className="font-serif text-[16px] font-bold text-[#1A1F1E]">Cardiac cine-MRI analysis</h3>
          </div>
          <p className="mt-1 pl-7 text-[13px] text-muted-foreground">
            FCT segmentation, VAE features, and ensemble classification from paired ED/ES NIfTI volumes.
          </p>
        </div>
        <Badge
          variant="default"
          className="w-fit rounded-lg border-0 bg-violet-500 px-2.5 py-1 text-[11px] font-bold text-white shadow-none hover:bg-violet-500"
        >
          AI · FCT + ensemble
        </Badge>
      </div>

      <div className="space-y-4">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          {edFile ? (
            <MriFileCard
              file={edFile}
              phase="ED"
              status={status}
              elapsed={elapsed}
              onRemove={handleRemoveEd}
            />
          ) : (
            <MriDropZone phase="ED" onFileSelected={handleEdFileSelected} />
          )}

          {esFile ? (
            <MriFileCard
              file={esFile}
              phase="ES"
              status={status}
              elapsed={elapsed}
              onRemove={handleRemoveEs}
            />
          ) : (
            <MriDropZone phase="ES" onFileSelected={handleEsFileSelected} />
          )}
        </div>

        {!bothFilesReady && (
          <p className="text-center text-[13px] text-muted-foreground">
            Upload both the{" "}
            <span className="font-semibold text-blue-600">end-diastolic (ED)</span> and{" "}
            <span className="font-semibold text-violet-600">end-systolic (ES)</span> NIfTI scans to run the analysis.
          </p>
        )}

        {status === "done" && result && (
          <>
            <MriResultPanel result={result} elapsedSec={result.elapsedSec || elapsed} />
            <Button
              type="button"
              size="sm"
              onClick={() => setAiChatOpen(true)}
              className="h-10 w-full gap-2 rounded-lg bg-violet-600 text-[13px] font-semibold hover:bg-violet-700"
            >
              <SparklesIcon className="size-4" aria-hidden />
              AI summary &amp; recommendations
            </Button>
            <CineMRIAiChatDialog
              open={aiChatOpen}
              onOpenChange={setAiChatOpen}
              result={result}
            />
          </>
        )}

        {status === "error" && (
          <MriErrorPanel message={errorMsg} onRetry={handleAnalyze} />
        )}

        {showAnalyzeButton && (
          <Button
            type="button"
            size="sm"
            disabled={status === "processing"}
            onClick={handleAnalyze}
            className="h-10 w-full gap-2 rounded-lg bg-[#1A5345] text-[13px] font-semibold hover:bg-[#133F34]"
          >
            {status === "processing" ? (
              <>
                <Loader2Icon className="size-4 animate-spin" aria-hidden />
                Running MRI pipeline…
              </>
            ) : (
              <>
                <BrainCircuitIcon className="size-4" aria-hidden />
                Run cardiac MRI analysis
              </>
            )}
          </Button>
        )}

        <p className="text-center text-[12px] leading-relaxed text-muted-foreground">
          Upload cardiac cine-MRI scans in NIfTI format (.nii / .nii.gz). Requires separate ED and ES phase files.
          Pipeline: FCT segmentation → VAE deep features + 20 manual clinical features → ensemble classification.
        </p>
      </div>
    </div>
  )
}
