import type { DoctorPrescriptionsPageData } from "./doctorPrescriptions.types"

const FIXED_DATE = new Date("2026-04-14T12:00:00Z")

function makeDate(dayOffset: number, hours: number, minutes: number): string {
  const d = new Date(FIXED_DATE)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

export const MOCK_DOCTOR_PRESCRIPTIONS: DoctorPrescriptionsPageData = {
  patients: [
    {
      id: "pat-101",
      fullName: "Ahmed Hassan",
      age: 58,
      gender: "male",
      condition: "Hypertension, Type 2 Diabetes",
    },
    {
      id: "pat-102",
      fullName: "Fatima Al-Rashid",
      age: 45,
      gender: "female",
      condition: "Atrial fibrillation",
    },
    {
      id: "pat-103",
      fullName: "Mohamed Youssef",
      age: 67,
      gender: "male",
      condition: "Coronary artery disease",
    },
    {
      id: "pat-104",
      fullName: "Sara Ibrahim",
      age: 52,
      gender: "female",
      condition: "Heart valve disease",
    },
    {
      id: "pat-105",
      fullName: "Omar Khalil",
      age: 61,
      gender: "male",
      condition: "Heart failure (NYHA Class II)",
    },
    {
      id: "pat-106",
      fullName: "Layla Mansour",
      age: 72,
      gender: "female",
      condition: "Peripheral artery disease",
    },
  ],
  prescriptions: [
    // Ahmed Hassan - pat-101
    {
      id: "med-101a",
      patientId: "pat-101",
      name: "Lisinopril",
      dose: "10 mg",
      frequency: "Once daily",
      type: "antihypertensives",
      compliance: "good",
      status: "active",
      prescribedAt: makeDate(-60, 0, 0),
      instructions: "Take in the morning. Monitor blood pressure regularly.",
      timeOfDay: ["morning"],
      adherencePercent: 95,
      lastTakenAt: makeDate(0, 7, 30),
    },
    {
      id: "med-101b",
      patientId: "pat-101",
      name: "Metformin",
      dose: "500 mg",
      frequency: "Twice daily",
      type: "diabetes_medications",
      compliance: "good",
      sideEffects: "Nausea, stomach upset",
      status: "active",
      prescribedAt: makeDate(-120, 0, 0),
      instructions: "Take with meals to reduce stomach upset.",
      timeOfDay: ["morning", "evening"],
      adherencePercent: 88,
      lastTakenAt: makeDate(0, 13, 0),
    },
    {
      id: "med-101c",
      patientId: "pat-101",
      name: "Atorvastatin",
      dose: "20 mg",
      frequency: "Once daily",
      type: "statins",
      compliance: "good",
      sideEffects: "Mild muscle ache",
      status: "active",
      prescribedAt: makeDate(-90, 0, 0),
      instructions: "Take at bedtime. Avoid grapefruit juice.",
      timeOfDay: ["evening"],
      adherencePercent: 92,
      lastTakenAt: makeDate(0, 20, 10),
    },
    // Fatima Al-Rashid - pat-102
    {
      id: "med-102a",
      patientId: "pat-102",
      name: "Warfarin",
      dose: "5 mg",
      frequency: "Once daily",
      type: "anticoagulants",
      compliance: "poor",
      sideEffects: "Easy bruising, prolonged bleeding",
      status: "active",
      prescribedAt: makeDate(-45, 0, 0),
      instructions: "Take at the same time daily. Regular INR checks required.",
      timeOfDay: ["evening"],
      adherencePercent: 55,
      lastTakenAt: makeDate(-1, 18, 0),
    },
    {
      id: "med-102b",
      patientId: "pat-102",
      name: "Metoprolol",
      dose: "50 mg",
      frequency: "Twice daily",
      type: "antiarrhythmics",
      compliance: "good",
      sideEffects: "Fatigue, dizziness",
      status: "active",
      prescribedAt: makeDate(-80, 0, 0),
      instructions: "Take with meals. Do not stop suddenly.",
      timeOfDay: ["morning", "evening"],
      adherencePercent: 90,
      lastTakenAt: makeDate(0, 8, 0),
    },
    // Mohamed Youssef - pat-103
    {
      id: "med-103a",
      patientId: "pat-103",
      name: "Aspirin",
      dose: "81 mg",
      frequency: "Once daily",
      type: "antiplatelets",
      compliance: "good",
      sideEffects: "Minor stomach irritation",
      status: "active",
      prescribedAt: makeDate(-180, 0, 0),
      instructions: "Take with food.",
      timeOfDay: ["morning"],
      adherencePercent: 97,
      lastTakenAt: makeDate(0, 8, 0),
    },
    {
      id: "med-103b",
      patientId: "pat-103",
      name: "Clopidogrel",
      dose: "75 mg",
      frequency: "Once daily",
      type: "antiplatelets",
      compliance: "good",
      status: "active",
      prescribedAt: makeDate(-30, 0, 0),
      instructions: "Post-angioplasty dual antiplatelet therapy. Do not discontinue.",
      timeOfDay: ["morning"],
      adherencePercent: 94,
      lastTakenAt: makeDate(0, 8, 15),
    },
    {
      id: "med-103c",
      patientId: "pat-103",
      name: "Atorvastatin",
      dose: "40 mg",
      frequency: "Once daily",
      type: "statins",
      compliance: "good",
      status: "active",
      prescribedAt: makeDate(-30, 0, 0),
      instructions: "High-intensity statin therapy post-angioplasty.",
      timeOfDay: ["evening"],
      adherencePercent: 91,
      lastTakenAt: makeDate(0, 21, 0),
    },
    // Sara Ibrahim - pat-104
    {
      id: "med-104a",
      patientId: "pat-104",
      name: "Furosemide",
      dose: "40 mg",
      frequency: "Once daily",
      type: "diuretics",
      compliance: "good",
      sideEffects: "Frequent urination",
      status: "active",
      prescribedAt: makeDate(-30, 0, 0),
      instructions: "Take in the morning. Monitor weight daily.",
      timeOfDay: ["morning"],
      adherencePercent: 85,
      lastTakenAt: makeDate(0, 7, 0),
    },
    {
      id: "med-104b",
      patientId: "pat-104",
      name: "Lisinopril",
      dose: "5 mg",
      frequency: "Once daily",
      type: "antihypertensives",
      compliance: "good",
      status: "active",
      prescribedAt: makeDate(-30, 0, 0),
      instructions: "Low dose for afterload reduction.",
      timeOfDay: ["morning"],
      adherencePercent: 93,
      lastTakenAt: makeDate(0, 7, 0),
    },
    // Omar Khalil - pat-105
    {
      id: "med-105a",
      patientId: "pat-105",
      name: "Carvedilol",
      dose: "12.5 mg",
      frequency: "Twice daily",
      type: "antihypertensives",
      compliance: "poor",
      sideEffects: "Dizziness, fatigue",
      status: "active",
      prescribedAt: makeDate(-90, 0, 0),
      instructions: "Take with food. Titrate up slowly. Monitor for worsening heart failure.",
      timeOfDay: ["morning", "evening"],
      adherencePercent: 42,
      lastTakenAt: makeDate(-2, 20, 0),
    },
    {
      id: "med-105b",
      patientId: "pat-105",
      name: "Furosemide",
      dose: "80 mg",
      frequency: "Once daily",
      type: "diuretics",
      compliance: "good",
      sideEffects: "Dehydration, electrolyte imbalance",
      status: "active",
      prescribedAt: makeDate(-90, 0, 0),
      instructions: "Take in the morning. Potassium supplement may be needed.",
      timeOfDay: ["morning"],
      adherencePercent: 78,
      lastTakenAt: makeDate(0, 7, 0),
    },
    {
      id: "med-105c",
      patientId: "pat-105",
      name: "Spironolactone",
      dose: "25 mg",
      frequency: "Once daily",
      type: "diuretics",
      compliance: "good",
      sideEffects: "Hyperkalemia risk",
      status: "active",
      prescribedAt: makeDate(-60, 0, 0),
      instructions: "Monitor potassium levels regularly.",
      timeOfDay: ["morning"],
      adherencePercent: 82,
      lastTakenAt: makeDate(0, 7, 0),
    },
    {
      id: "med-105d",
      patientId: "pat-105",
      name: "Sacubitril/Valsartan",
      dose: "24/26 mg",
      frequency: "Twice daily",
      type: "antihypertensives",
      compliance: "poor",
      status: "active",
      prescribedAt: makeDate(-45, 0, 0),
      instructions: "ARNI therapy for HFrEF. Do not combine with ACE inhibitors.",
      timeOfDay: ["morning", "evening"],
      adherencePercent: 38,
      lastTakenAt: makeDate(-3, 8, 0),
    },
    // Layla Mansour - pat-106
    {
      id: "med-106a",
      patientId: "pat-106",
      name: "Cilostazol",
      dose: "100 mg",
      frequency: "Twice daily",
      type: "antiplatelets",
      compliance: "good",
      sideEffects: "Headache, palpitations",
      status: "active",
      prescribedAt: makeDate(-40, 0, 0),
      instructions: "Take 30 minutes before or 2 hours after meals.",
      timeOfDay: ["morning", "evening"],
      adherencePercent: 86,
      lastTakenAt: makeDate(0, 7, 30),
    },
    {
      id: "med-106b",
      patientId: "pat-106",
      name: "Atorvastatin",
      dose: "40 mg",
      frequency: "Once daily",
      type: "statins",
      compliance: "good",
      status: "active",
      prescribedAt: makeDate(-40, 0, 0),
      instructions: "Take at bedtime for lipid management.",
      timeOfDay: ["evening"],
      adherencePercent: 91,
      lastTakenAt: makeDate(0, 20, 0),
    },
    {
      id: "med-106c",
      patientId: "pat-106",
      name: "Pentoxifylline",
      dose: "400 mg",
      frequency: "Three times daily",
      type: "antiplatelets",
      compliance: "poor",
      sideEffects: "Nausea, dizziness",
      status: "discontinued",
      prescribedAt: makeDate(-100, 0, 0),
      instructions: "Discontinued due to side effects.",
      timeOfDay: ["morning", "afternoon", "evening"],
      adherencePercent: 30,
      lastTakenAt: makeDate(-20, 12, 0),
    },
  ],
  stats: {
    totalPatients: 6,
    totalPrescriptions: 17,
    activePrescriptions: 15,
    poorComplianceCount: 4,
  },
}
