import type { DoctorPatientsPageData, PatientFullRecord, ConsultationReport } from "./doctorPatients.types"

export const mockDoctorPatientsData: DoctorPatientsPageData = {
  stats: {
    totalPatients: 24,
    highRiskCount: 7,
    complianceAlertsCount: 5,
  },
  patients: [
    {
      id: "P-001",
      fullName: "Ahmed Al-Rashid",
      dateOfBirth: "1968-03-15",
      gender: "male",
      bloodType: "A+",
      phone: "+20 100 123 4567",
      email: "ahmed.rashid@email.com",
      address: "12 Nasr City, Cairo",
      condition: "Essential Hypertension (Stage II), T2DM, Dyslipidemia",
      activeMedications: 4,
      poorComplianceCount: 1,
      lastVisitDate: "2026-03-28",
      upcomingAppointmentDate: "2026-04-17",
      riskLevel: "high",
      allergies: [
        { id: "al-001-1", category: "drug", allergen: "Penicillin", reaction: "Anaphylaxis" },
        { id: "al-001-2", category: "drug", allergen: "Sulfonamides", reaction: "Rash" },
        { id: "al-001-3", category: "food", allergen: "Shellfish", reaction: "Urticaria" },
      ],
      familyHistory: [
        { id: "fh-001-1", relationship: "Father", condition: "Myocardial Infarction", details: "MI at age 52, fatal" },
        { id: "fh-001-2", relationship: "Mother", condition: "Type 2 Diabetes", details: "" },
        { id: "fh-001-3", relationship: "Brother", condition: "Hypertension", details: "" },
      ],
      smokingStatus: "Former (quit 5 yrs ago, 20 pack-years)",
      bmi: 31.2,
      totalVisits: 18,
      patientSince: "2019-06-10",
      profileImageUrl: null,
      occupation: "Retired Engineer",
      maritalStatus: "Married",
      nationalId: "29901011234567",
    },
    {
      id: "P-002",
      fullName: "Fatima Hassan",
      dateOfBirth: "1975-07-22",
      gender: "female",
      bloodType: "O-",
      phone: "+20 100 234 5678",
      email: "fatima.hassan@email.com",
      address: "45 Maadi, Cairo",
      condition: "Atrial Fibrillation, Hypertension",
      activeMedications: 3,
      poorComplianceCount: 0,
      lastVisitDate: "2026-04-02",
      upcomingAppointmentDate: "2026-04-20",
      riskLevel: "moderate",
      allergies: [{ id: "al-002-1", category: "other", allergen: "Latex", reaction: "Contact dermatitis" }],
      familyHistory: [
        { id: "fh-002-1", relationship: "Mother", condition: "Breast Cancer", details: "" },
      ],
      smokingStatus: "Never",
      bmi: 26.5,
      totalVisits: 12,
      patientSince: "2021-03-15",
      profileImageUrl: null,
      occupation: "Teacher",
      maritalStatus: "Married",
      nationalId: "28507221234567",
    },
    {
      id: "P-003",
      fullName: "Mohamed Youssef",
      dateOfBirth: "1955-11-08",
      gender: "male",
      bloodType: "B+",
      phone: "+20 111 456 7890",
      email: "mohamed.y@email.com",
      address: "78 Heliopolis, Cairo",
      condition: "Coronary Artery Disease, Heart Failure (NYHA II)",
      activeMedications: 6,
      poorComplianceCount: 2,
      lastVisitDate: "2026-04-10",
      upcomingAppointmentDate: "2026-04-18",
      riskLevel: "high",
      allergies: [],
      familyHistory: [
        { id: "fh-003-1", relationship: "Father", condition: "Coronary Artery Disease", details: "" },
        { id: "fh-003-2", relationship: "Brother", condition: "Myocardial Infarction", details: "MI at age 48" },
      ],
      smokingStatus: "Current (15 cig/day)",
      bmi: 28.4,
      totalVisits: 34,
      patientSince: "2018-01-20",
      profileImageUrl: null,
      occupation: "Retired Accountant",
      maritalStatus: "Widowed",
      nationalId: "27511081234567",
    },
    {
      id: "P-004",
      fullName: "Sara Ibrahim",
      dateOfBirth: "1982-01-30",
      gender: "female",
      bloodType: "AB+",
      phone: "+20 122 567 8901",
      email: "sara.ib@email.com",
      address: "23 Zamalek, Cairo",
      condition: "Hypertension (Stage I)",
      activeMedications: 1,
      poorComplianceCount: 0,
      lastVisitDate: "2026-04-05",
      upcomingAppointmentDate: null,
      riskLevel: "low",
      allergies: [{ id: "al-004-1", category: "drug", allergen: "Aspirin", reaction: "GI upset" }],
      familyHistory: [],
      smokingStatus: "Never",
      bmi: 23.8,
      totalVisits: 6,
      patientSince: "2024-09-12",
      profileImageUrl: null,
      occupation: "Software Developer",
      maritalStatus: "Single",
      nationalId: "30201301234567",
    },
    {
      id: "P-005",
      fullName: "Omar Abdel-Aziz",
      dateOfBirth: "1960-09-12",
      gender: "male",
      bloodType: "A-",
      phone: "+20 133 678 9012",
      email: "omar.aziz@email.com",
      address: "56 Garden City, Cairo",
      condition: "Aortic Stenosis (Moderate), Hypertension",
      activeMedications: 3,
      poorComplianceCount: 0,
      lastVisitDate: "2026-03-20",
      upcomingAppointmentDate: "2026-04-22",
      riskLevel: "moderate",
      allergies: [],
      familyHistory: [
        { id: "fh-005-1", relationship: "Father", condition: "Aortic Stenosis", details: "" },
      ],
      smokingStatus: "Former (quit 10 yrs ago)",
      bmi: 27.1,
      totalVisits: 22,
      patientSince: "2020-05-08",
      profileImageUrl: null,
      occupation: "Business Owner",
      maritalStatus: "Married",
      nationalId: "26009121234567",
    },
    {
      id: "P-006",
      fullName: "Layla Mostafa",
      dateOfBirth: "1990-05-18",
      gender: "female",
      bloodType: "O+",
      phone: "+20 100 345 6789",
      email: "layla.m@email.com",
      address: "89 Dokki, Giza",
      condition: "Palpitations, Anxiety",
      activeMedications: 1,
      poorComplianceCount: 0,
      lastVisitDate: "2026-04-12",
      upcomingAppointmentDate: null,
      riskLevel: "low",
      allergies: [],
      familyHistory: [],
      smokingStatus: "Never",
      bmi: 22.0,
      totalVisits: 3,
      patientSince: "2026-02-10",
      profileImageUrl: null,
      occupation: "Graphic Designer",
      maritalStatus: "Single",
      nationalId: "29005181234567",
    },
    {
      id: "P-007",
      fullName: "Youssef Kamel",
      dateOfBirth: "1948-12-03",
      gender: "male",
      bloodType: "B-",
      phone: "+20 144 789 0123",
      email: "youssef.k@email.com",
      address: "34 Shoubra, Cairo",
      condition: "Heart Failure (NYHA III), T2DM, CKD Stage III",
      activeMedications: 7,
      poorComplianceCount: 3,
      lastVisitDate: "2026-04-14",
      upcomingAppointmentDate: "2026-04-17",
      riskLevel: "high",
      allergies: [
        { id: "al-006-1", category: "drug", allergen: "ACE Inhibitors", reaction: "Cough" },
        { id: "al-006-2", category: "other", allergen: "Iodine Contrast", reaction: "Anaphylactoid reaction" },
      ],
      familyHistory: [
        { id: "fh-007-1", relationship: "Father", condition: "Heart Failure", details: "" },
        { id: "fh-007-2", relationship: "Mother", condition: "Type 2 Diabetes", details: "" },
      ],
      smokingStatus: "Former (quit 2 yrs ago, 30 pack-years)",
      bmi: 29.8,
      totalVisits: 41,
      patientSince: "2017-08-22",
      profileImageUrl: null,
      occupation: "Retired Teacher",
      maritalStatus: "Married",
      nationalId: "24812031234567",
    },
    {
      id: "P-008",
      fullName: "Nadia Selim",
      dateOfBirth: "1965-06-25",
      gender: "female",
      bloodType: "A+",
      phone: "+20 155 890 1234",
      email: "nadia.s@email.com",
      address: "67 Mohandessin, Giza",
      condition: "Dyslipidemia, Hypothyroidism",
      activeMedications: 2,
      poorComplianceCount: 0,
      lastVisitDate: "2026-04-01",
      upcomingAppointmentDate: "2026-04-25",
      riskLevel: "low",
      allergies: [],
      familyHistory: [
        { id: "fh-008-1", relationship: "Mother", condition: "Hypothyroidism", details: "" },
      ],
      smokingStatus: "Never",
      bmi: 25.3,
      totalVisits: 15,
      patientSince: "2020-11-30",
      profileImageUrl: null,
      occupation: "Pharmacist",
      maritalStatus: "Married",
      nationalId: "26506251234567",
    },
    {
      id: "P-009",
      fullName: "Hassan Mahmoud",
      dateOfBirth: "1970-04-10",
      gender: "male",
      bloodType: "O+",
      phone: "+20 166 901 2345",
      email: "hassan.m@email.com",
      address: "90 October City, Giza",
      condition: "Hypertension (Stage II), Obesity",
      activeMedications: 2,
      poorComplianceCount: 1,
      lastVisitDate: "2026-03-15",
      upcomingAppointmentDate: null,
      riskLevel: "moderate",
      allergies: [],
      familyHistory: [
        { id: "fh-009-1", relationship: "Father", condition: "Hypertension", details: "" },
        { id: "fh-009-2", relationship: "Mother", condition: "Obesity", details: "" },
      ],
      smokingStatus: "Current (10 cig/day)",
      bmi: 35.6,
      totalVisits: 9,
      patientSince: "2023-02-14",
      profileImageUrl: null,
      occupation: "Civil Engineer",
      maritalStatus: "Married",
      nationalId: "27004101234567",
    },
    {
      id: "P-010",
      fullName: "Amira Farouk",
      dateOfBirth: "1958-08-07",
      gender: "female",
      bloodType: "AB-",
      phone: "+20 177 012 3456",
      email: "amira.f@email.com",
      address: "12 New Cairo, Cairo",
      condition: "Post-MI, Hypertension, Dyslipidemia",
      activeMedications: 5,
      poorComplianceCount: 0,
      lastVisitDate: "2026-04-08",
      upcomingAppointmentDate: "2026-04-19",
      riskLevel: "high",
      allergies: [{ id: "al-010-1", category: "drug", allergen: "NSAIDs", reaction: "GI bleeding" }],
      familyHistory: [
        { id: "fh-010-1", relationship: "Father", condition: "Myocardial Infarction", details: "" },
        { id: "fh-010-2", relationship: "Sister", condition: "Stroke", details: "" },
      ],
      smokingStatus: "Former (quit 1 yr ago, 25 pack-years)",
      bmi: 27.9,
      totalVisits: 28,
      patientSince: "2019-09-05",
      profileImageUrl: null,
      occupation: "Retired Nurse",
      maritalStatus: "Widowed",
      nationalId: "25808071234567",
    },
  ],
}

export const mockPatientFullRecord: PatientFullRecord = {
  patient: mockDoctorPatientsData.patients[0],
  latestVitals: {
    id: "vr-latest",
    date: "2026-04-17",
    time: "09:05",
    source: "clinic",
    systolicBP: 148,
    diastolicBP: 92,
    heartRate: 78,
    oxygenSaturation: 97,
    temperature: 36.8,
    weight: 87,
    bloodSugar: 142,
    notes: "Patient reports dizziness in mornings",
  },
  vitalReadings: [
    { id: "vr-1", date: "2026-04-17", time: "09:05", source: "clinic", systolicBP: 148, diastolicBP: 92, heartRate: 78, oxygenSaturation: 97, temperature: 36.8, weight: 87, bloodSugar: 142, notes: "Dizziness in mornings" },
    { id: "vr-2", date: "2026-04-10", time: "08:30", source: "home", systolicBP: 142, diastolicBP: 88, heartRate: 74, oxygenSaturation: 98, temperature: null, weight: null, bloodSugar: 128, notes: "" },
    { id: "vr-3", date: "2026-04-08", time: "07:45", source: "home", systolicBP: 155, diastolicBP: 95, heartRate: 82, oxygenSaturation: 96, temperature: null, weight: null, bloodSugar: 160, notes: "After heavy meal" },
    { id: "vr-4", date: "2026-04-05", time: "18:20", source: "home", systolicBP: 138, diastolicBP: 85, heartRate: 72, oxygenSaturation: 98, temperature: null, weight: null, bloodSugar: 118, notes: "" },
    { id: "vr-5", date: "2026-04-01", time: "08:00", source: "home", systolicBP: 145, diastolicBP: 90, heartRate: 76, oxygenSaturation: 97, temperature: null, weight: 87.2, bloodSugar: 135, notes: "" },
    { id: "vr-6", date: "2026-03-28", time: "10:15", source: "clinic", systolicBP: 152, diastolicBP: 94, heartRate: 80, oxygenSaturation: 97, temperature: 37.0, weight: 87.5, bloodSugar: 150, notes: "Routine follow-up" },
    { id: "vr-7", date: "2026-03-20", time: "07:30", source: "home", systolicBP: 140, diastolicBP: 86, heartRate: 70, oxygenSaturation: 98, temperature: null, weight: null, bloodSugar: 122, notes: "" },
    { id: "vr-8", date: "2026-03-15", time: "19:00", source: "home", systolicBP: 160, diastolicBP: 98, heartRate: 88, oxygenSaturation: 95, temperature: null, weight: null, bloodSugar: 175, notes: "Stressful day at work" },
  ],
  medications: [
    { id: "med-1", name: "Amlodipine", dose: "5 mg", frequency: "Once daily", type: "antihypertensives", status: "active", prescribedAt: "2024-03-15", prescribedBy: "Dr. Mahmoud", adherencePercent: 92, sideEffects: null, lastTakenAt: "2026-04-17T08:00" },
    { id: "med-2", name: "Atorvastatin", dose: "20 mg", frequency: "Once daily", type: "statins", status: "active", prescribedAt: "2023-06-10", prescribedBy: "Dr. Mahmoud", adherencePercent: 85, sideEffects: "Mild muscle pain", lastTakenAt: "2026-04-17T07:30" },
    { id: "med-3", name: "Metformin", dose: "500 mg", frequency: "Twice daily", type: "diabetes_medications", status: "active", prescribedAt: "2024-01-20", prescribedBy: "Dr. El-Sayed", adherencePercent: 78, sideEffects: null, lastTakenAt: "2026-04-17T08:00" },
    { id: "med-4", name: "Aspirin", dose: "81 mg", frequency: "Once daily", type: "antiplatelets", status: "active", prescribedAt: "2023-06-10", prescribedBy: "Dr. Mahmoud", adherencePercent: 95, sideEffects: null, lastTakenAt: "2026-04-17T07:30" },
    { id: "med-5", name: "Lisinopril", dose: "10 mg", frequency: "Once daily", type: "antihypertensives", status: "active", prescribedAt: "2025-11-10", prescribedBy: "Dr. Mahmoud", adherencePercent: 88, sideEffects: "Occasional dry cough", lastTakenAt: "2026-04-17T08:00" },
    { id: "med-6", name: "Hydrochlorothiazide", dose: "25 mg", frequency: "Once daily", type: "diuretics", status: "discontinued", prescribedAt: "2023-06-10", prescribedBy: "Dr. Mahmoud", adherencePercent: 60, sideEffects: "Frequent urination, dizziness", lastTakenAt: "2025-11-08T08:00" },
  ],
  diagnoses: [
    { id: "dx-1", icdCode: "I10", description: "Essential (Primary) Hypertension", category: "cardiac", chronicFlag: true, infectiousFlag: false, type: "primary", severity: "severe", diagnosedAt: "2019-06-10", diagnosedBy: "Dr. Mahmoud", status: "chronic", notes: "Stage II, currently uncontrolled. Target <130/80 for diabetic patients.", createdAt: "2019-06-10T09:00:00.000Z", updatedAt: "2026-04-10T14:30:00.000Z" },
    { id: "dx-2", icdCode: "E11.9", description: "Type 2 Diabetes Mellitus without complications", category: "diabetes", chronicFlag: true, infectiousFlag: false, type: "primary", severity: "moderate", diagnosedAt: "2020-02-20", diagnosedBy: "Dr. El-Sayed", status: "chronic", notes: "HbA1c 7.2% as of last labs. On Metformin.", createdAt: "2020-02-20T11:15:00.000Z", updatedAt: "2026-04-10T14:30:00.000Z" },
    { id: "dx-3", icdCode: "E78.5", description: "Dyslipidemia, Unspecified", category: "cardiac", chronicFlag: true, infectiousFlag: false, type: "secondary", severity: "moderate", diagnosedAt: "2019-06-10", diagnosedBy: "Dr. Mahmoud", status: "chronic", notes: "LDL 160 mg/dL. On Atorvastatin 20mg.", createdAt: "2019-06-10T09:00:00.000Z", updatedAt: "2026-03-28T10:00:00.000Z" },
    { id: "dx-4", icdCode: "E66.01", description: "Morbid Obesity", category: "other", chronicFlag: true, infectiousFlag: false, type: "secondary", severity: "moderate", diagnosedAt: "2019-06-10", diagnosedBy: "Dr. Mahmoud", status: "chronic", notes: "BMI 31.2. Counseled on diet and exercise.", createdAt: "2019-06-10T09:00:00.000Z", updatedAt: "2026-01-15T08:45:00.000Z" },
    { id: "dx-5", icdCode: "F17.210", description: "Nicotine dependence, cigarettes, uncomplicated", category: "pulmonary", chronicFlag: false, infectiousFlag: false, type: "secondary", severity: "mild", diagnosedAt: "2019-06-10", diagnosedBy: "Dr. Mahmoud", status: "resolved", notes: "Quit 5 years ago after 20 pack-year history.", createdAt: "2019-06-10T09:00:00.000Z", updatedAt: "2024-11-02T16:20:00.000Z" },
  ],
  labResults: [
    { id: "lab-1", panelId: "panel-001", panelTitle: "HbA1c & glucose panel", source: "upload", documentId: "doc-6", testName: "HbA1c", value: "7.2", unit: "%", referenceRange: "< 6.5%", status: "high", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-2", panelId: "panel-001", panelTitle: "HbA1c & glucose panel", source: "upload", documentId: "doc-6", testName: "Fasting Blood Sugar", value: "142", unit: "mg/dL", referenceRange: "70-100 mg/dL", status: "high", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-3", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "Total Cholesterol", value: "238", unit: "mg/dL", referenceRange: "< 200 mg/dL", status: "high", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-4", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "LDL Cholesterol", value: "160", unit: "mg/dL", referenceRange: "< 100 mg/dL", status: "high", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-5", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "HDL Cholesterol", value: "38", unit: "mg/dL", referenceRange: "> 40 mg/dL", status: "low", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-6", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "Triglycerides", value: "210", unit: "mg/dL", referenceRange: "< 150 mg/dL", status: "high", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-7", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "Serum Creatinine", value: "1.1", unit: "mg/dL", referenceRange: "0.7-1.3 mg/dL", status: "normal", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-8", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "BUN", value: "18", unit: "mg/dL", referenceRange: "7-20 mg/dL", status: "normal", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-9", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "Sodium", value: "140", unit: "mEq/L", referenceRange: "136-145 mEq/L", status: "normal", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-10", panelId: "panel-002", panelTitle: "Lipid & metabolic panel", source: "upload", documentId: "doc-3", testName: "Potassium", value: "4.2", unit: "mEq/L", referenceRange: "3.5-5.0 mEq/L", status: "normal", date: "2026-04-10", orderedBy: "Dr. Mahmoud" },
    { id: "lab-11", panelId: "panel-003", panelTitle: "Thyroid panel", source: "manual", testName: "TSH", value: "2.8", unit: "mIU/L", referenceRange: "0.4-4.0 mIU/L", status: "normal", date: "2026-03-28", orderedBy: "Dr. Mahmoud" },
    { id: "lab-12", panelId: "panel-004", panelTitle: "Complete blood count", source: "manual", testName: "Complete Blood Count", value: "Normal", unit: "", referenceRange: "", status: "normal", date: "2026-03-28", orderedBy: "Dr. Mahmoud" },
  ],
  documents: [
    { id: "doc-1", fileName: "ECG_2026-04-17.pdf", type: "ecg", uploadedAt: "2026-04-17", uploadedBy: "Dr. Mahmoud", fileSize: "1.2 MB" },
    { id: "doc-2", fileName: "Echocardiogram_2026-03-28.pdf", type: "imaging", uploadedAt: "2026-03-28", uploadedBy: "Cardiology Lab", fileSize: "4.8 MB" },
    { id: "doc-3", fileName: "Lipid_Panel_2026-04-10.pdf", type: "lab_report", uploadedAt: "2026-04-10", uploadedBy: "Lab Services", fileSize: "320 KB" },
    { id: "doc-4", fileName: "Chest_XRay_2026-02-15.pdf", type: "imaging", uploadedAt: "2026-02-15", uploadedBy: "Radiology", fileSize: "2.1 MB" },
    { id: "doc-5", fileName: "Referral_Cardiology_2019-06-10.pdf", type: "referral", uploadedAt: "2019-06-10", uploadedBy: "Dr. Abbas", fileSize: "150 KB" },
    { id: "doc-6", fileName: "HbA1c_Report_2026-04-10.pdf", type: "lab_report", uploadedAt: "2026-04-10", uploadedBy: "Lab Services", fileSize: "280 KB" },
  ],
  visits: [
    { id: "v-1", date: "2026-04-17", type: "follow-up", doctorName: "Dr. Mahmoud", chiefComplaint: "Routine follow-up, dizziness", diagnosisSummary: "Uncontrolled HTN, T2DM follow-up", notes: "BP elevated. Consider adjusting Amlodipine. Review HbA1c.", durationMin: 20 },
    { id: "v-2", date: "2026-03-28", type: "follow-up", doctorName: "Dr. Mahmoud", chiefComplaint: "Routine follow-up", diagnosisSummary: "Hypertension follow-up, dyslipidemia management", notes: "Labs ordered. Echocardiogram normal EF 58%.", durationMin: 20 },
    { id: "v-3", date: "2026-02-20", type: "follow-up", doctorName: "Dr. El-Sayed", chiefComplaint: "Blood sugar monitoring", diagnosisSummary: "T2DM — HbA1c improved from 7.8% to 7.2%", notes: "Continue Metformin. Diet counseling reinforced.", durationMin: 15 },
    { id: "v-4", date: "2026-01-15", type: "follow-up", doctorName: "Dr. Mahmoud", chiefComplaint: "Headache, fatigue", diagnosisSummary: "BP poorly controlled on current regimen", notes: "Added Lisinopril 10mg. Discontinued HCTZ due to dizziness.", durationMin: 25 },
    { id: "v-5", date: "2025-11-10", type: "follow-up", doctorName: "Dr. Mahmoud", chiefComplaint: "Routine follow-up", diagnosisSummary: "Annual review — all conditions stable", notes: "Flu vaccine administered. Lipid panel ordered.", durationMin: 30 },
    { id: "v-6", date: "2025-08-05", type: "walk-in", doctorName: "Dr. Mahmoud", chiefComplaint: "Chest discomfort", diagnosisSummary: "Non-cardiac chest pain — GERD", notes: "ECG normal. Referred to GI. Prescribed Omeprazole.", durationMin: 35 },
    { id: "v-7", date: "2025-05-12", type: "follow-up", doctorName: "Dr. Mahmoud", chiefComplaint: "Routine follow-up", diagnosisSummary: "All conditions stable", notes: "Weight stable. Continue current medications.", durationMin: 15 },
    { id: "v-8", date: "2025-02-03", type: "follow-up", doctorName: "Dr. El-Sayed", chiefComplaint: "Blood sugar monitoring", diagnosisSummary: "T2DM — HbA1c 7.8%", notes: "Increased Metformin to 500mg BID. Diet counseling.", durationMin: 20 },
  ],
  profileClinicalNotes: [],
  careGoals: [],
}

export const mockConsultationReports: Record<string, ConsultationReport> = {
  "v-1": {
    visitId: "v-1",
    patientId: "p-001",
    date: "2026-04-17",
    time: "09:15",
    doctorName: "Dr. Mahmoud",
    doctorSpecialty: "Cardiology",
    type: "follow-up",
    durationMin: 20,
    chiefComplaint: "Routine follow-up, dizziness in mornings for the past 2 weeks",
    historyOfPresentIllness: "Patient reports episodic dizziness upon waking, lasting 5\u201310 minutes. No syncope, chest pain, or palpitations. Symptoms began approximately 2 weeks ago. Blood pressure readings at home have been elevated (140\u2013160/88\u201398). No change in medication adherence. Diet has been inconsistent due to Ramadan fasting schedule.",
    vitals: {
      systolicBP: 148,
      diastolicBP: 92,
      heartRate: 78,
      oxygenSaturation: 97,
      temperature: 36.8,
      weight: 87,
      bloodSugar: 142,
    },
    physicalExam: "General: Alert, oriented, no acute distress. CV: Regular rate and rhythm, no murmurs, JVP normal. Lungs: Clear to auscultation bilaterally. Abdomen: Soft, non-tender, no organomegaly. Extremities: No edema, peripheral pulses intact.",
    diagnoses: [
      { icdCode: "I10", description: "Essential Hypertension (Stage II) \u2014 Uncontrolled", type: "primary" },
      { icdCode: "E11.9", description: "Type 2 Diabetes Mellitus \u2014 Suboptimal control", type: "primary" },
      { icdCode: "E78.5", description: "Dyslipidemia", type: "secondary" },
    ],
    prescriptions: [
      { id: "cp-1", name: "Amlodipine", dose: "10 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
      { id: "cp-2", name: "Lisinopril", dose: "10 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
      { id: "cp-3", name: "Metformin", dose: "500 mg", frequency: "Twice daily", duration: "Ongoing", isNew: false },
      { id: "cp-4", name: "Atorvastatin", dose: "20 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
      { id: "cp-5", name: "Aspirin", dose: "81 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
    ],
    labOrders: ["HbA1c", "Lipid Panel", "Fasting Blood Sugar", "Serum Creatinine", "Electrolytes"],
    referrals: [
      { specialty: "Endocrinology", reason: "Suboptimal T2DM control — consider treatment escalation", urgency: "routine" },
      { specialty: "Ophthalmology", reason: "Annual diabetic retinopathy screening overdue", urgency: "routine" },
    ],
    plan: "1. Increase Amlodipine from 5mg to 10mg daily for better BP control.\n2. Continue current diabetes regimen; reassess after HbA1c results.\n3. Reinforce dietary counseling, especially during Ramadan.\n4. Order follow-up labs in 2 weeks.\n5. Home BP monitoring twice daily, keep log.",
    clinicalNotes: "Patient was advised on gradual position changes in the morning to reduce dizziness. Counseling provided on importance of medication timing during fasting hours.",
    assessmentAndPlan: "1. Increase Amlodipine from 5mg to 10mg daily for better BP control.\n2. Continue current diabetes regimen; reassess after HbA1c results.\n3. Reinforce dietary counseling, especially during Ramadan.\n4. Order follow-up labs in 2 weeks.\n5. Home BP monitoring twice daily, keep log.",
    medicalHistorySummary: "Hypertension and type 2 diabetes on file. No new cardiac events reported.",
    procedureDetailsSummary: "",
    homeMeasurements: [{ metric: "blood_pressure", frequency: "twice_daily", notes: "Keep a home log" }],
    sessionTestOrders: [
      { id: "lo-1", tests: ["HbA1c", "Lipid Panel", "Fasting Blood Sugar", "Serum Creatinine", "Electrolytes"], priority: "routine", status: "ordered", notes: null },
    ],
    aiStudies: [],
    followUp: { timeframe: "2 weeks", instructions: "Return with home BP log and lab results. If dizziness worsens or new symptoms develop, seek urgent care." },
    notes: "Patient was advised on gradual position changes in the morning to reduce dizziness. Counseling provided on importance of medication timing during fasting hours.",
    patientInstructions: {
      diagnosisSummary: "Your blood pressure and diabetes need closer control. We are adjusting your medications and will recheck labs soon.",
      lifestyleAdvice: "• Take medications at the same time each day.\n• Reduce salt and fried foods; choose vegetables and whole grains.\n• Check blood pressure at home twice daily and keep a log.\n• During Ramadan, discuss medication timing with your care team.",
      dangerSigns: "Go to the emergency department immediately if you have severe chest pain, fainting, sudden confusion, or trouble breathing at rest.",
    },
  },
  "v-2": {
    visitId: "v-2",
    patientId: "p-001",
    date: "2026-03-28",
    time: "10:30",
    doctorName: "Dr. Mahmoud",
    doctorSpecialty: "Cardiology",
    type: "follow-up",
    durationMin: 20,
    chiefComplaint: "Routine follow-up",
    historyOfPresentIllness: "Patient presents for routine follow-up. No new complaints. Reports good medication adherence. Home BP readings have been variable (130\u2013150/82\u201394). Blood sugar levels have been acceptable. No chest pain, shortness of breath, or edema.",
    vitals: {
      systolicBP: 152,
      diastolicBP: 94,
      heartRate: 80,
      oxygenSaturation: 97,
      temperature: 37.0,
      weight: 87.5,
      bloodSugar: 150,
    },
    physicalExam: "General: Well-appearing, no acute distress. CV: Regular rate and rhythm. Lungs: Clear. Abdomen: Soft, non-tender. Extremities: Trace bilateral ankle edema.",
    diagnoses: [
      { icdCode: "I10", description: "Essential Hypertension (Stage II)", type: "primary" },
      { icdCode: "E78.5", description: "Dyslipidemia \u2014 Needs reassessment", type: "primary" },
    ],
    prescriptions: [
      { id: "cp-6", name: "Amlodipine", dose: "5 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
      { id: "cp-7", name: "Lisinopril", dose: "10 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
    ],
    labOrders: ["Lipid Panel", "HbA1c", "Complete Blood Count"],
    referrals: [],
    plan: "1. Order comprehensive lab work including lipid panel and HbA1c.\n2. Order echocardiogram to assess cardiac function.\n3. Continue current medications pending lab results.\n4. Follow up in 3 weeks with results.",
    clinicalNotes: "Echocardiogram ordered. Patient counseled on sodium restriction and weight management.",
    assessmentAndPlan: "1. Order comprehensive lab work including lipid panel and HbA1c.\n2. Order echocardiogram to assess cardiac function.\n3. Continue current medications pending lab results.\n4. Follow up in 3 weeks with results.",
    medicalHistorySummary: "Known hypertension and dyslipidemia.",
    procedureDetailsSummary: "",
    homeMeasurements: [],
    sessionTestOrders: [
      { id: "lo-2", tests: ["Lipid Panel", "HbA1c", "Complete Blood Count"], priority: "routine", status: "ordered", notes: null },
    ],
    aiStudies: [],
    followUp: { timeframe: "3 weeks", instructions: "Return with lab results and echocardiogram report." },
    notes: "Echocardiogram ordered. Patient counseled on sodium restriction and weight management.",
    patientInstructions: {
      diagnosisSummary: "You have high blood pressure and cholesterol that we are monitoring with labs and an echocardiogram.",
      lifestyleAdvice: "• Limit added salt and processed foods.\n• Walk regularly if you feel well.\n• Continue all prescribed medications unless told otherwise.",
      dangerSigns: "Seek emergency care for crushing chest pain, severe breathlessness, or fainting.",
    },
  },
  "v-3": {
    visitId: "v-3",
    patientId: "p-001",
    date: "2026-02-20",
    time: "11:00",
    doctorName: "Dr. El-Sayed",
    doctorSpecialty: "Endocrinology",
    type: "follow-up",
    durationMin: 15,
    chiefComplaint: "Blood sugar monitoring",
    historyOfPresentIllness: "Follow-up for T2DM management. Patient reports improved dietary compliance. Home glucose readings: fasting 110\u2013140 mg/dL, postprandial 150\u2013190 mg/dL. No hypoglycemic episodes.",
    vitals: {
      systolicBP: 138,
      diastolicBP: 86,
      heartRate: 74,
      oxygenSaturation: 98,
      temperature: 36.7,
      weight: 87.8,
      bloodSugar: 128,
    },
    physicalExam: "General: Well-appearing. No diabetic foot changes. Sensation intact bilaterally. Fundoscopic exam: no retinopathy.",
    diagnoses: [
      { icdCode: "E11.9", description: "Type 2 Diabetes Mellitus \u2014 Improving", type: "primary" },
    ],
    prescriptions: [
      { id: "cp-8", name: "Metformin", dose: "500 mg", frequency: "Twice daily", duration: "Ongoing", isNew: false },
    ],
    labOrders: ["HbA1c"],
    referrals: [
      { specialty: "Ophthalmology", reason: "Annual diabetic retinopathy screening", urgency: "routine" },
    ],
    plan: "1. Continue Metformin 500mg BID.\n2. HbA1c improved from 7.8% to 7.2% \u2014 good progress.\n3. Reinforce diet and exercise counseling.\n4. Aim for HbA1c <7% at next visit.",
    clinicalNotes: "Patient motivated by improvement. Diet counseling reinforced. Encouraged 30 min daily walking.",
    assessmentAndPlan: "1. Continue Metformin 500mg BID.\n2. HbA1c improved from 7.8% to 7.2% \u2014 good progress.\n3. Reinforce diet and exercise counseling.\n4. Aim for HbA1c <7% at next visit.",
    medicalHistorySummary: "Type 2 diabetes mellitus.",
    procedureDetailsSummary: "",
    homeMeasurements: [],
    sessionTestOrders: [{ id: "lo-3", tests: ["HbA1c"], priority: "routine", status: "ordered", notes: null }],
    aiStudies: [],
    followUp: { timeframe: "3 months", instructions: "Continue home glucose monitoring. Return for routine diabetes follow-up." },
    notes: "Patient motivated by improvement. Diet counseling reinforced. Encouraged 30 min daily walking.",
    patientInstructions: {
      diagnosisSummary: "Your diabetes control is improving. Keep up your current plan while we work toward a lower long-term blood sugar target.",
      lifestyleAdvice: "• Continue Metformin as prescribed.\n• Aim for balanced meals and regular walking.\n• Monitor blood sugar as directed and bring your log to follow-up.",
      dangerSigns: "Go to emergency care if you have confusion, persistent vomiting, or signs of very low blood sugar that do not improve with sugar intake.",
    },
  },
  "v-6": {
    visitId: "v-6",
    patientId: "p-001",
    date: "2025-08-05",
    time: "14:20",
    doctorName: "Dr. Mahmoud",
    doctorSpecialty: "Cardiology",
    type: "walk-in",
    durationMin: 35,
    chiefComplaint: "Chest discomfort",
    historyOfPresentIllness: "Patient presents with substernal chest discomfort that began 1 hour ago after a heavy meal. Described as burning, non-radiating, worse with lying down. No diaphoresis, shortness of breath, or radiation to arm/jaw. Similar episode 3 months ago, resolved with antacids.",
    vitals: {
      systolicBP: 140,
      diastolicBP: 88,
      heartRate: 86,
      oxygenSaturation: 98,
      temperature: 37.1,
      weight: 88,
      bloodSugar: 160,
    },
    physicalExam: "General: Mildly anxious, no acute distress. CV: Regular rate and rhythm, no murmurs. Lungs: Clear. Abdomen: Epigastric tenderness on palpation. ECG: Normal sinus rhythm, no ST changes.",
    diagnoses: [
      { icdCode: "K21.0", description: "GERD (Gastroesophageal Reflux Disease)", type: "primary" },
      { icdCode: "I10", description: "Essential Hypertension \u2014 Assessment", type: "secondary" },
    ],
    prescriptions: [
      { id: "cp-9", name: "Omeprazole", dose: "20 mg", frequency: "Once daily before breakfast", duration: "4 weeks", isNew: true },
      { id: "cp-10", name: "Aspirin", dose: "81 mg", frequency: "Once daily", duration: "Ongoing", isNew: false },
    ],
    labOrders: ["Troponin I", "CK-MB", "Complete Blood Count"],
    referrals: [
      { specialty: "Gastroenterology", reason: "Recurrent epigastric discomfort — evaluate for GERD complications, consider endoscopy", urgency: "routine" },
    ],
    plan: "1. ECG normal, cardiac enzymes ordered to rule out ACS.\n2. Likely GERD based on history and epigastric tenderness.\n3. Prescribe Omeprazole 20mg daily for 4 weeks.\n4. GI referral for endoscopy if symptoms persist.\n5. Avoid large meals before lying down.",
    clinicalNotes: "Cardiac workup negative. Patient reassured. GI referral placed.",
    assessmentAndPlan: "1. ECG normal, cardiac enzymes ordered to rule out ACS.\n2. Likely GERD based on history and epigastric tenderness.\n3. Prescribe Omeprazole 20mg daily for 4 weeks.\n4. GI referral for endoscopy if symptoms persist.\n5. Avoid large meals before lying down.",
    medicalHistorySummary: "Episodic epigastric discomfort. Hypertension under assessment.",
    procedureDetailsSummary: "",
    homeMeasurements: [],
    sessionTestOrders: [{ id: "lo-4", tests: ["Troponin I", "CK-MB", "Complete Blood Count"], priority: "urgent", status: "ordered", notes: "Rule out ACS" }],
    aiStudies: [],
    followUp: { timeframe: "4 weeks", instructions: "Return if symptoms worsen or do not improve. Seek emergency care if severe chest pain, shortness of breath, or sweating develops." },
    notes: "Cardiac workup negative. Patient reassured. GI referral placed.",
    patientInstructions: {
      diagnosisSummary: "Today's symptoms are most likely from acid reflux (GERD), not a heart attack. We ordered tests to be safe and started treatment.",
      lifestyleAdvice: "• Take omeprazole before breakfast daily.\n• Avoid large meals late at night and lying down right after eating.\n• Limit spicy, fatty, and acidic foods if they trigger symptoms.",
      dangerSigns: "Go to emergency immediately for severe crushing chest pain, pain spreading to jaw or arm, sweating with chest pain, or sudden severe breathlessness.",
    },
  },
}
